// ------------------------------------------------------------------
// ⚠️ AUTO-GENERATED FROM docs/mockups/coverage.json
// ------------------------------------------------------------------
// Run: npx ignite scaffold
// (or via npx tsx scripts/ignite.ts scaffold)

export enum CtaId {
  CTA_ADD_STUDENT = "cta-add-student",
  CTA_ADMIN_BOOK_BACK = "cta-admin-book-back",
  CTA_ADMIN_BOOK_REFRESH = "cta-admin-book-refresh",
  CTA_ADMIN_BOOKMISSING_ARTIFACT_OPEN = "cta-admin-bookmissing-artifact-open",
  CTA_ADMIN_BOOKMISSING_BACK = "cta-admin-bookmissing-back",
  CTA_ADMIN_BOOKMISSING_BOOK_SELECT = "cta-admin-bookmissing-book-select",
  CTA_ADMIN_BOOKMISSING_OPEN_PDF = "cta-admin-bookmissing-open-pdf",
  CTA_ADMIN_BOOKMISSING_REFRESH = "cta-admin-bookmissing-refresh",
  CTA_ADMIN_BOOKMISSING_RERENDER = "cta-admin-bookmissing-rerender",
  CTA_ADMIN_BOOKMISSING_RUN_SELECT = "cta-admin-bookmissing-run-select",
  CTA_ADMIN_BOOKRUN_BACK = "cta-admin-bookrun-back",
  CTA_ADMIN_BOOKRUN_MISSING_AI_GENERATE = "cta-admin-bookrun-missing-ai-generate",
  CTA_ADMIN_BOOKRUN_MISSING_REFRESH = "cta-admin-bookrun-missing-refresh",
  CTA_ADMIN_BOOKRUN_MISSING_UPLOAD = "cta-admin-bookrun-missing-upload",
  CTA_ADMIN_BOOKRUN_REFRESH = "cta-admin-bookrun-refresh",
  CTA_ADMIN_BOOKS_INGEST = "cta-admin-books-ingest",
  CTA_ADMIN_BOOKS_INGEST_BOOKID = "cta-admin-books-ingest-bookid",
  CTA_ADMIN_BOOKS_INGEST_CANONICAL_FILE = "cta-admin-books-ingest-canonical-file",
  CTA_ADMIN_BOOKS_INGEST_FIGURES_FILE = "cta-admin-books-ingest-figures-file",
  CTA_ADMIN_BOOKS_INGEST_LEVEL = "cta-admin-books-ingest-level",
  CTA_ADMIN_BOOKS_INGEST_SOURCE = "cta-admin-books-ingest-source",
  CTA_ADMIN_BOOKS_INGEST_TITLE = "cta-admin-books-ingest-title",
  CTA_ADMIN_BOOKS_INGEST_TOKENS_FILE = "cta-admin-books-ingest-tokens-file",
  CTA_ADMIN_BOOKS_REFRESH = "cta-admin-books-refresh",
  CTA_ADMIN_BOOKVERSION_ALLOW_MISSING_IMAGES = "cta-admin-bookversion-allow-missing-images",
  CTA_ADMIN_BOOKVERSION_BACK = "cta-admin-bookversion-back",
  CTA_ADMIN_BOOKVERSION_BOOKGEN_PRO = "cta-admin-bookversion-bookgen-pro",
  CTA_ADMIN_BOOKVERSION_CHAPTERINDEX = "cta-admin-bookversion-chapterindex",
  CTA_ADMIN_BOOKVERSION_CREATE_OVERLAY = "cta-admin-bookversion-create-overlay",
  CTA_ADMIN_BOOKVERSION_ENQUEUE_BOOK = "cta-admin-bookversion-enqueue-book",
  CTA_ADMIN_BOOKVERSION_ENQUEUE_CHAPTER = "cta-admin-bookversion-enqueue-chapter",
  CTA_ADMIN_BOOKVERSION_EXPORT_COURSEID = "cta-admin-bookversion-export-courseid",
  CTA_ADMIN_BOOKVERSION_EXPORT_STUDYTEXTS = "cta-admin-bookversion-export-studytexts",
  CTA_ADMIN_BOOKVERSION_NEW_OVERLAY_LABEL = "cta-admin-bookversion-new-overlay-label",
  CTA_ADMIN_BOOKVERSION_OVERLAYID = "cta-admin-bookversion-overlayid",
  CTA_ADMIN_BOOKVERSION_REFRESH = "cta-admin-bookversion-refresh",
  CTA_ADMIN_BOOKVERSION_RENDER_PROVIDER = "cta-admin-bookversion-render-provider",
  CTA_ADMIN_LIBRARY_COURSE_BACK = "cta-admin-library-course-back",
  CTA_ADMIN_LIBRARY_COURSES_FORMAT = "cta-admin-library-courses-format",
  CTA_ADMIN_LIBRARY_COURSES_NEXT = "cta-admin-library-courses-next",
  CTA_ADMIN_LIBRARY_COURSES_OPEN = "cta-admin-library-courses-open",
  CTA_ADMIN_LIBRARY_COURSES_PAGE_SIZE = "cta-admin-library-courses-page-size",
  CTA_ADMIN_LIBRARY_COURSES_PREV = "cta-admin-library-courses-prev",
  CTA_ADMIN_LIBRARY_COURSES_REFRESH = "cta-admin-library-courses-refresh",
  CTA_ADMIN_LIBRARY_COURSES_SEARCH = "cta-admin-library-courses-search",
  CTA_ADMIN_OVERLAY_BACK = "cta-admin-overlay-back",
  CTA_ADMIN_OVERLAY_CLEAR_SELECTION = "cta-admin-overlay-clear-selection",
  CTA_ADMIN_OVERLAY_DERIVED_COURSEID = "cta-admin-overlay-derived-courseid",
  CTA_ADMIN_OVERLAY_GENERATE_EXERCISES = "cta-admin-overlay-generate-exercises",
  CTA_ADMIN_OVERLAY_ONLY_EDITED = "cta-admin-overlay-only-edited",
  CTA_ADMIN_OVERLAY_REFRESH = "cta-admin-overlay-refresh",
  CTA_ADMIN_OVERLAY_SAVE = "cta-admin-overlay-save",
  CTA_ADMIN_OVERLAY_SEARCH = "cta-admin-overlay-search",
  CTA_ADMIN_OVERLAY_SELECT_ALL = "cta-admin-overlay-select-all",
  CTA_BOOKGEN_BACK = "cta-bookgen-back",
  CTA_BOOKGEN_BOOKID = "cta-bookgen-bookid",
  CTA_BOOKGEN_CHAPTERS = "cta-bookgen-chapters",
  CTA_BOOKGEN_CLONE_BOOK = "cta-bookgen-clone-book",
  CTA_BOOKGEN_DOCS = "cta-bookgen-docs",
  CTA_BOOKGEN_HISTORY = "cta-bookgen-history",
  CTA_BOOKGEN_IMAGES_FILTER_ALL = "cta-bookgen-images-filter-all",
  CTA_BOOKGEN_IMAGES_FILTER_CHAPTER = "cta-bookgen-images-filter-chapter",
  CTA_BOOKGEN_IMAGES_FILTER_COMPLETE = "cta-bookgen-images-filter-complete",
  CTA_BOOKGEN_IMAGES_FILTER_PENDING = "cta-bookgen-images-filter-pending",
  CTA_BOOKGEN_IMAGES_GENERATE_ALL = "cta-bookgen-images-generate-all",
  CTA_BOOKGEN_IMAGES_RENDER_PREVIEW = "cta-bookgen-images-render-preview",
  CTA_BOOKGEN_IMG_GENERATE_1 = "cta-bookgen-img-generate-1",
  CTA_BOOKGEN_IMG_GENERATE_2 = "cta-bookgen-img-generate-2",
  CTA_BOOKGEN_IMG_GENERATE_4 = "cta-bookgen-img-generate-4",
  CTA_BOOKGEN_IMG_REMOVE_3 = "cta-bookgen-img-remove-3",
  CTA_BOOKGEN_IMG_REPLACE_3 = "cta-bookgen-img-replace-3",
  CTA_BOOKGEN_IMG_UPLOAD_1 = "cta-bookgen-img-upload-1",
  CTA_BOOKGEN_IMG_UPLOAD_2 = "cta-bookgen-img-upload-2",
  CTA_BOOKGEN_IMG_UPLOAD_4 = "cta-bookgen-img-upload-4",
  CTA_BOOKGEN_IMPORT_SKELETON = "cta-bookgen-import-skeleton",
  CTA_BOOKGEN_LANGUAGE = "cta-bookgen-language",
  CTA_BOOKGEN_LEVEL = "cta-bookgen-level",
  CTA_BOOKGEN_OPEN_EDITOR = "cta-bookgen-open-editor",
  CTA_BOOKGEN_PACK_BUSINESS = "cta-bookgen-pack-business",
  CTA_BOOKGEN_PACK_GENERAL = "cta-bookgen-pack-general",
  CTA_BOOKGEN_PACK_MEDICAL = "cta-bookgen-pack-medical",
  CTA_BOOKGEN_PACK_TECHNICAL = "cta-bookgen-pack-technical",
  CTA_BOOKGEN_PRESET_BALANCED = "cta-bookgen-preset-balanced",
  CTA_BOOKGEN_PRESET_CUSTOM = "cta-bookgen-preset-custom",
  CTA_BOOKGEN_PRESET_FAST = "cta-bookgen-preset-fast",
  CTA_BOOKGEN_PRESET_QUALITY = "cta-bookgen-preset-quality",
  CTA_BOOKGEN_PREVIEW_JSON = "cta-bookgen-preview-json",
  CTA_BOOKGEN_PREVIEW_OUTLINE = "cta-bookgen-preview-outline",
  CTA_BOOKGEN_RENDER_FINAL = "cta-bookgen-render-final",
  CTA_BOOKGEN_SAVE_DRAFT = "cta-bookgen-save-draft",
  CTA_BOOKGEN_SKELETON_CLAUDE = "cta-bookgen-skeleton-claude",
  CTA_BOOKGEN_SKELETON_GPT4O = "cta-bookgen-skeleton-gpt4o",
  CTA_BOOKGEN_STAGE_COMPILE_CONFIG = "cta-bookgen-stage-compile-config",
  CTA_BOOKGEN_STAGE_IMAGES_CONFIG = "cta-bookgen-stage-images-config",
  CTA_BOOKGEN_STAGE_SKELETON_CONFIG = "cta-bookgen-stage-skeleton-config",
  CTA_BOOKGEN_STAGE_VALIDATE_CONFIG = "cta-bookgen-stage-validate-config",
  CTA_BOOKGEN_STAGE_WRITE_CONFIG = "cta-bookgen-stage-write-config",
  CTA_BOOKGEN_START = "cta-bookgen-start",
  CTA_BOOKGEN_TOPIC = "cta-bookgen-topic",
  CTA_BOOKGEN_VALIDATE_CLAUDE = "cta-bookgen-validate-claude",
  CTA_BOOKGEN_VALIDATE_GPT4O = "cta-bookgen-validate-gpt4o",
  CTA_BOOKGEN_WRITE_CLAUDE_OPUS = "cta-bookgen-write-claude-opus",
  CTA_BOOKGEN_WRITE_CLAUDE_SONNET = "cta-bookgen-write-claude-sonnet",
  CTA_BOOKGEN_WRITE_GPT4O = "cta-bookgen-write-gpt4o",
  CTA_BOOKGEN_WRITE_O1 = "cta-bookgen-write-o1",
  CTA_BOOKMONITOR_BOOK_SELECT = "cta-bookmonitor-book-select",
  CTA_BOOKMONITOR_CHAPTER_CELL = "cta-bookmonitor-chapter-cell",
  CTA_BOOKSTUDIO_ADD_BOOK = "cta-bookstudio-add-book",
  CTA_BOOKSTUDIO_BACK_TO_BOOK = "cta-bookstudio-back-to-book",
  CTA_BOOKSTUDIO_BACK_TO_LIBRARY = "cta-bookstudio-back-to-library",
  CTA_BOOKSTUDIO_BOOK_ARCHIVE = "cta-bookstudio-book-archive",
  CTA_BOOKSTUDIO_BOOK_EXPORT = "cta-bookstudio-book-export",
  CTA_BOOKSTUDIO_BOOK_MISSING_IMAGES = "cta-bookstudio-book-missing-images",
  CTA_BOOKSTUDIO_BOOK_REFRESH = "cta-bookstudio-book-refresh",
  CTA_BOOKSTUDIO_BOOK_RENDER = "cta-bookstudio-book-render",
  CTA_BOOKSTUDIO_BOOK_RUNS = "cta-bookstudio-book-runs",
  CTA_BOOKSTUDIO_BOOK_VERSIONS = "cta-bookstudio-book-versions",
  CTA_BOOKSTUDIO_CHAPTER_AI_REWRITE_ALL = "cta-bookstudio-chapter-ai-rewrite-all",
  CTA_BOOKSTUDIO_CHAPTER_DISCARD = "cta-bookstudio-chapter-discard",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_0 = "cta-bookstudio-chapter-edit-0",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_1 = "cta-bookstudio-chapter-edit-1",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_2 = "cta-bookstudio-chapter-edit-2",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_3 = "cta-bookstudio-chapter-edit-3",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_4 = "cta-bookstudio-chapter-edit-4",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_5 = "cta-bookstudio-chapter-edit-5",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_0 = "cta-bookstudio-chapter-opener-0",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_1 = "cta-bookstudio-chapter-opener-1",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_2 = "cta-bookstudio-chapter-opener-2",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_3 = "cta-bookstudio-chapter-opener-3",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_4 = "cta-bookstudio-chapter-opener-4",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_5 = "cta-bookstudio-chapter-opener-5",
  CTA_BOOKSTUDIO_CHAPTER_SAVE = "cta-bookstudio-chapter-save",
  CTA_BOOKSTUDIO_COVER_AI = "cta-bookstudio-cover-ai",
  CTA_BOOKSTUDIO_COVER_UPLOAD = "cta-bookstudio-cover-upload",
  CTA_BOOKSTUDIO_DIFF_TOGGLE_SPLIT = "cta-bookstudio-diff-toggle-split",
  CTA_BOOKSTUDIO_DIFF_TOGGLE_UNIFIED = "cta-bookstudio-diff-toggle-unified",
  CTA_BOOKSTUDIO_FILTER_ALL = "cta-bookstudio-filter-all",
  CTA_BOOKSTUDIO_FILTER_DRAFT = "cta-bookstudio-filter-draft",
  CTA_BOOKSTUDIO_FILTER_N3 = "cta-bookstudio-filter-n3",
  CTA_BOOKSTUDIO_FILTER_N4 = "cta-bookstudio-filter-n4",
  CTA_BOOKSTUDIO_FILTER_PUBLISHED = "cta-bookstudio-filter-published",
  CTA_BOOKSTUDIO_GENERATE = "cta-bookstudio-generate",
  CTA_BOOKSTUDIO_INGEST_NEW = "cta-bookstudio-ingest-new",
  CTA_BOOKSTUDIO_INSPECTOR_AI_REWRITE = "cta-bookstudio-inspector-ai-rewrite",
  CTA_BOOKSTUDIO_INSPECTOR_CLEAR_SELECTION = "cta-bookstudio-inspector-clear-selection",
  CTA_BOOKSTUDIO_INSPECTOR_HTML = "cta-bookstudio-inspector-html",
  CTA_BOOKSTUDIO_INSPECTOR_REVERT = "cta-bookstudio-inspector-revert",
  CTA_BOOKSTUDIO_NAV_SECTION_0 = "cta-bookstudio-nav-section-0",
  CTA_BOOKSTUDIO_NAV_SECTION_1 = "cta-bookstudio-nav-section-1",
  CTA_BOOKSTUDIO_NAV_SECTION_2 = "cta-bookstudio-nav-section-2",
  CTA_BOOKSTUDIO_NAV_SECTION_3 = "cta-bookstudio-nav-section-3",
  CTA_BOOKSTUDIO_NAV_SECTION_4 = "cta-bookstudio-nav-section-4",
  CTA_BOOKSTUDIO_OPEN_ANATOMIE_N3 = "cta-bookstudio-open-anatomie_n3",
  CTA_BOOKSTUDIO_OPEN_FARMACOLOGIE_N4 = "cta-bookstudio-open-farmacologie_n4",
  CTA_BOOKSTUDIO_OPEN_PATHOLOGIE_N4 = "cta-bookstudio-open-pathologie_n4",
  CTA_BOOKSTUDIO_OPEN_PSYCHIATRIE_N3 = "cta-bookstudio-open-psychiatrie_n3",
  CTA_BOOKSTUDIO_OPEN_VERPLEEGKUNDE_N4 = "cta-bookstudio-open-verpleegkunde_n4",
  CTA_BOOKSTUDIO_PARA_AI_REWRITE_0 = "cta-bookstudio-para-ai-rewrite-0",
  CTA_BOOKSTUDIO_PARA_AI_REWRITE_1 = "cta-bookstudio-para-ai-rewrite-1",
  CTA_BOOKSTUDIO_PARA_AI_REWRITE_2 = "cta-bookstudio-para-ai-rewrite-2",
  CTA_BOOKSTUDIO_PARA_EDIT_0 = "cta-bookstudio-para-edit-0",
  CTA_BOOKSTUDIO_PARA_EDIT_2 = "cta-bookstudio-para-edit-2",
  CTA_BOOKSTUDIO_PARA_IMAGE_AI_1 = "cta-bookstudio-para-image-ai-1",
  CTA_BOOKSTUDIO_PARA_IMAGE_REMOVE_2 = "cta-bookstudio-para-image-remove-2",
  CTA_BOOKSTUDIO_PARA_IMAGE_REPLACE_2 = "cta-bookstudio-para-image-replace-2",
  CTA_BOOKSTUDIO_PARA_IMAGE_UPLOAD_1 = "cta-bookstudio-para-image-upload-1",
  CTA_BOOKSTUDIO_PARA_MICROHEAD_0 = "cta-bookstudio-para-microhead-0",
  CTA_BOOKSTUDIO_PARA_REVERT_0 = "cta-bookstudio-para-revert-0",
  CTA_BOOKSTUDIO_PARA_REVERT_1 = "cta-bookstudio-para-revert-1",
  CTA_BOOKSTUDIO_PARA_REVERT_2 = "cta-bookstudio-para-revert-2",
  CTA_BOOKSTUDIO_PARA_SAVE_1 = "cta-bookstudio-para-save-1",
  CTA_BOOKSTUDIO_PARA_SELECT_REWRITE_0 = "cta-bookstudio-para-select-rewrite-0",
  CTA_BOOKSTUDIO_PARA_SUGGEST_MICROHEAD_0 = "cta-bookstudio-para-suggest-microhead-0",
  CTA_BOOKSTUDIO_PARA_TEXT_1 = "cta-bookstudio-para-text-1",
  CTA_BOOKSTUDIO_PROOF_OPEN = "cta-bookstudio-proof-open",
  CTA_BOOKSTUDIO_PROOF_OPEN_RUN = "cta-bookstudio-proof-open-run",
  CTA_BOOKSTUDIO_PROOF_REFRESH = "cta-bookstudio-proof-refresh",
  CTA_BOOKSTUDIO_REFRESH = "cta-bookstudio-refresh",
  CTA_BOOKSTUDIO_REVERT_TO_V2 = "cta-bookstudio-revert-to-v2",
  CTA_BOOKSTUDIO_REWRITE_ALL_BOOK = "cta-bookstudio-rewrite-all-book",
  CTA_BOOKSTUDIO_SEARCH = "cta-bookstudio-search",
  CTA_BOOKSTUDIO_SECTION_ADD_IMAGE = "cta-bookstudio-section-add-image",
  CTA_BOOKSTUDIO_SECTION_AI_REWRITE = "cta-bookstudio-section-ai-rewrite",
  CTA_BOOKSTUDIO_VERSION_COMPARE = "cta-bookstudio-version-compare",
  CTA_BOOKSTUDIO_VERSION_DIFF_1 = "cta-bookstudio-version-diff-1",
  CTA_BOOKSTUDIO_VERSION_DIFF_2 = "cta-bookstudio-version-diff-2",
  CTA_BOOKSTUDIO_VERSION_ITEM_1 = "cta-bookstudio-version-item-1",
  CTA_BOOKSTUDIO_VERSION_ITEM_2 = "cta-bookstudio-version-item-2",
  CTA_BOOKSTUDIO_VERSION_ITEM_3 = "cta-bookstudio-version-item-3",
  CTA_BOOKSTUDIO_VERSION_PUBLISH = "cta-bookstudio-version-publish",
  CTA_BOOKSTUDIO_VERSION_REVERT_1 = "cta-bookstudio-version-revert-1",
  CTA_BOOKSTUDIO_VERSION_REVERT_2 = "cta-bookstudio-version-revert-2",
  CTA_BOOKSTUDIO_VERSION_SELECT_1 = "cta-bookstudio-version-select-1",
  CTA_BOOKSTUDIO_VERSION_SELECT_2 = "cta-bookstudio-version-select-2",
  CTA_BOOKSTUDIO_VERSIONS_BACK = "cta-bookstudio-versions-back",
  CTA_BOOKSTUDIO_VERSIONS_EXPORT = "cta-bookstudio-versions-export",
  CTA_BOOKSTUDIO_VIEW_EDIT = "cta-bookstudio-view-edit",
  CTA_BOOKSTUDIO_VIEW_PROOF = "cta-bookstudio-view-proof",
  CTA_BOOKSTUDIO_WYSIWYG_ZOOM = "cta-bookstudio-wysiwyg-zoom",
  CTA_CANCEL = "cta-cancel",
  CTA_COURSEEDITOR_CLOSE = "cta-courseeditor-close",
  CTA_COURSEEDITOR_COMMAND_ARCHIVE = "cta-courseeditor-command-archive",
  CTA_COURSEEDITOR_COMMAND_AUDIT_VARIANTS = "cta-courseeditor-command-audit-variants",
  CTA_COURSEEDITOR_COMMAND_COPILOT_ENRICH = "cta-courseeditor-command-copilot-enrich",
  CTA_COURSEEDITOR_COMMAND_COPILOT_VARIANTS = "cta-courseeditor-command-copilot-variants",
  CTA_COURSEEDITOR_COMMAND_DELETE = "cta-courseeditor-command-delete",
  CTA_COURSEEDITOR_COMMAND_DISCARD = "cta-courseeditor-command-discard",
  CTA_COURSEEDITOR_COMMAND_GENERATE_MISSING_VARIANTS = "cta-courseeditor-command-generate-missing-variants",
  CTA_COURSEEDITOR_COMMAND_LOCALIZE = "cta-courseeditor-command-localize",
  CTA_COURSEEDITOR_COMMAND_PALETTE = "cta-courseeditor-command-palette",
  CTA_COURSEEDITOR_COMMAND_PUBLISH = "cta-courseeditor-command-publish",
  CTA_COURSEEDITOR_COMMAND_REPAIR = "cta-courseeditor-command-repair",
  CTA_COURSEEDITOR_COMMAND_SAVE = "cta-courseeditor-command-save",
  CTA_COURSEEDITOR_DISCARD = "cta-courseeditor-discard",
  CTA_COURSEEDITOR_EDITOR_TAB_EXERCISES = "cta-courseeditor-editor-tab-exercises",
  CTA_COURSEEDITOR_EDITOR_TAB_EXPLANATION = "cta-courseeditor-editor-tab-explanation",
  CTA_COURSEEDITOR_EDITOR_TAB_OPTIONS = "cta-courseeditor-editor-tab-options",
  CTA_COURSEEDITOR_EDITOR_TAB_STEM = "cta-courseeditor-editor-tab-stem",
  CTA_COURSEEDITOR_EXERCISES_GENERATE = "cta-courseeditor-exercises-generate",
  CTA_COURSEEDITOR_EXPLANATION_AI_REWRITE = "cta-courseeditor-explanation-ai-rewrite",
  CTA_COURSEEDITOR_FAB_ADD_IMAGE_AI = "cta-courseeditor-fab-add-image-ai",
  CTA_COURSEEDITOR_FAB_AI_REWRITE_STEM = "cta-courseeditor-fab-ai-rewrite-stem",
  CTA_COURSEEDITOR_FAB_GENERATE_EXERCISES = "cta-courseeditor-fab-generate-exercises",
  CTA_COURSEEDITOR_FAB_TOGGLE = "cta-courseeditor-fab-toggle",
  CTA_COURSEEDITOR_ITEM_ADD_IMAGE_AI = "cta-courseeditor-item-add-image-ai",
  CTA_COURSEEDITOR_ITEM_FIX_MISSING_IMAGES = "cta-courseeditor-item-fix-missing-images",
  CTA_COURSEEDITOR_MEDIA_FILTER_ALL = "cta-courseeditor-media-filter-all",
  CTA_COURSEEDITOR_MEDIA_FILTER_AUDIO = "cta-courseeditor-media-filter-audio",
  CTA_COURSEEDITOR_MEDIA_FILTER_IMAGES = "cta-courseeditor-media-filter-images",
  CTA_COURSEEDITOR_MEDIA_FILTER_VIDEO = "cta-courseeditor-media-filter-video",
  CTA_COURSEEDITOR_MEDIA_SELECT_0 = "cta-courseeditor-media-select-0",
  CTA_COURSEEDITOR_MEDIA_SELECT_1 = "cta-courseeditor-media-select-1",
  CTA_COURSEEDITOR_MEDIA_SELECT_2 = "cta-courseeditor-media-select-2",
  CTA_COURSEEDITOR_MEDIA_SELECT_3 = "cta-courseeditor-media-select-3",
  CTA_COURSEEDITOR_MEDIA_SELECT_4 = "cta-courseeditor-media-select-4",
  CTA_COURSEEDITOR_MEDIA_SELECT_5 = "cta-courseeditor-media-select-5",
  CTA_COURSEEDITOR_MEDIA_TOGGLE = "cta-courseeditor-media-toggle",
  CTA_COURSEEDITOR_MODE_SELECT = "cta-courseeditor-mode-select",
  CTA_COURSEEDITOR_NAV_ADD_GROUP = "cta-courseeditor-nav-add-group",
  CTA_COURSEEDITOR_NAV_COLLAPSE_ALL = "cta-courseeditor-nav-collapse-all",
  CTA_COURSEEDITOR_NAV_GROUP_TOGGLE_0 = "cta-courseeditor-nav-group-toggle-0",
  CTA_COURSEEDITOR_NAV_GROUP_TOGGLE_1 = "cta-courseeditor-nav-group-toggle-1",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_0 = "cta-courseeditor-nav-item-select-0-0",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_1 = "cta-courseeditor-nav-item-select-0-1",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_2 = "cta-courseeditor-nav-item-select-0-2",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_3 = "cta-courseeditor-nav-item-select-0-3",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_4 = "cta-courseeditor-nav-item-select-0-4",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_5 = "cta-courseeditor-nav-item-select-0-5",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_1_0 = "cta-courseeditor-nav-item-select-1-0",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_1_1 = "cta-courseeditor-nav-item-select-1-1",
  CTA_COURSEEDITOR_OPTION_0_ADD_MEDIA = "cta-courseeditor-option-0-add-media",
  CTA_COURSEEDITOR_OPTION_0_AI_REWRITE = "cta-courseeditor-option-0-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_1_ADD_MEDIA = "cta-courseeditor-option-1-add-media",
  CTA_COURSEEDITOR_OPTION_1_AI_REWRITE = "cta-courseeditor-option-1-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_2_ADD_MEDIA = "cta-courseeditor-option-2-add-media",
  CTA_COURSEEDITOR_OPTION_2_AI_REWRITE = "cta-courseeditor-option-2-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_3_ADD_MEDIA = "cta-courseeditor-option-3-add-media",
  CTA_COURSEEDITOR_OPTION_3_AI_REWRITE = "cta-courseeditor-option-3-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_ADD = "cta-courseeditor-option-add",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_1 = "cta-courseeditor-option-mark-correct-1",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_2 = "cta-courseeditor-option-mark-correct-2",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_3 = "cta-courseeditor-option-mark-correct-3",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_0 = "cta-courseeditor-preview-option-select-0",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_1 = "cta-courseeditor-preview-option-select-1",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_2 = "cta-courseeditor-preview-option-select-2",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_3 = "cta-courseeditor-preview-option-select-3",
  CTA_COURSEEDITOR_PREVIEW_REFRESH = "cta-courseeditor-preview-refresh",
  CTA_COURSEEDITOR_PUBLISH = "cta-courseeditor-publish",
  CTA_COURSEEDITOR_SAVE = "cta-courseeditor-save",
  CTA_COURSEEDITOR_STEM_AI_REWRITE = "cta-courseeditor-stem-ai-rewrite",
  CTA_COURSEEDITOR_STEM_MEDIA_LIBRARY = "cta-courseeditor-stem-media-library",
  CTA_COURSEEDITOR_STEM_PREVIEW = "cta-courseeditor-stem-preview",
  CTA_COURSEEDITOR_STEM_UPLOAD_MEDIA = "cta-courseeditor-stem-upload-media",
  CTA_COURSEEDITOR_TAB_EXERCISES = "cta-courseeditor-tab-exercises",
  CTA_COURSEEDITOR_TAB_STUDYTEXTS = "cta-courseeditor-tab-studytexts",
  CTA_CREATE_CLASS = "cta-create-class",
  CTA_ECGEN_CLEAR = "cta-ecgen-clear",
  CTA_ECGEN_SAVE_TO_COURSE = "cta-ecgen-save-to-course",
  CTA_ECGEN_SCOPE_COURSE = "cta-ecgen-scope-course",
  CTA_ECGEN_SCOPE_SELECTED = "cta-ecgen-scope-selected",
  CTA_ECGEN_SCOPE_SINGLE = "cta-ecgen-scope-single",
  CTA_ECGEN_SELECT_ALL = "cta-ecgen-select-all",
  CTA_ECGEN_START = "cta-ecgen-start",
  CTA_GENERATE_ALL = "cta-generate-all",
  CTA_GENERATE_CHAPTER = "cta-generate-chapter",
  CTA_GENERATE_CLASS_CODE = "cta-generate-class-code",
  CTA_JOIN_CLASS = "cta-join-class",
  CTA_KW1C_KD_CODE = "cta-kw1c-kd-code",
  CTA_KW1C_LANGUAGE = "cta-kw1c-language",
  CTA_KW1C_OPEN_CLASSES = "cta-kw1c-open-classes",
  CTA_KW1C_OPEN_LESSON_KITS = "cta-kw1c-open-lesson-kits",
  CTA_KW1C_OPEN_MATERIALS = "cta-kw1c-open-materials",
  CTA_KW1C_OPEN_MES = "cta-kw1c-open-mes",
  CTA_KW1C_OPEN_RESULT = "cta-kw1c-open-result",
  CTA_KW1C_OPEN_STANDARDS = "cta-kw1c-open-standards",
  CTA_KW1C_OPEN_STUDENTS = "cta-kw1c-open-students",
  CTA_KW1C_OPEN_TEACHERGPT_CHAT = "cta-kw1c-open-teachergpt-chat",
  CTA_KW1C_QUERY = "cta-kw1c-query",
  CTA_KW1C_REFRESH = "cta-kw1c-refresh",
  CTA_KW1C_SEARCH = "cta-kw1c-search",
  CTA_KW1C_TO_TEACHER_DASHBOARD = "cta-kw1c-to-teacher-dashboard",
  CTA_KW1C_TYPE = "cta-kw1c-type",
  CTA_LINK_CHILD = "cta-link-child",
  CTA_PAUSE = "cta-pause",
  CTA_REMOVE_STUDENT = "cta-remove-student",
  CTA_RENDER_PDF = "cta-render-pdf",
  CTA_RESUME = "cta-resume",
  CTA_TEACHER_LESSON_KITS_AUTO_REPAIR = "cta-teacher-lesson-kits-auto-repair",
  CTA_TEACHER_LESSON_KITS_HTML = "cta-teacher-lesson-kits-html",
  CTA_TEACHER_LESSON_KITS_MODULE_ID = "cta-teacher-lesson-kits-module-id",
  CTA_TEACHER_LESSON_KITS_PROTOCOL = "cta-teacher-lesson-kits-protocol",
  CTA_TEACHER_LESSON_KITS_SUBMIT = "cta-teacher-lesson-kits-submit",
  CTA_TEACHER_MATERIALS_FILE = "cta-teacher-materials-file",
  CTA_TEACHER_MATERIALS_REFRESH = "cta-teacher-materials-refresh",
  CTA_TEACHER_MATERIALS_RESET = "cta-teacher-materials-reset",
  CTA_TEACHER_MATERIALS_TITLE = "cta-teacher-materials-title",
  CTA_TEACHER_MATERIALS_UPLOAD_AND_INGEST = "cta-teacher-materials-upload-and-ingest",
  CTA_TEACHER_STANDARDS_EXPORT = "cta-teacher-standards-export",
  CTA_TEACHER_STANDARDS_FILE = "cta-teacher-standards-file",
  CTA_TEACHER_STANDARDS_LOCALE = "cta-teacher-standards-locale",
  CTA_TEACHER_STANDARDS_MAP = "cta-teacher-standards-map",
  CTA_TEACHER_STANDARDS_REFRESH = "cta-teacher-standards-refresh",
  CTA_TEACHER_STANDARDS_RESET = "cta-teacher-standards-reset",
  CTA_TEACHER_STANDARDS_SELECT_MATERIAL = "cta-teacher-standards-select-material",
  CTA_TEACHER_STANDARDS_SELECT_STANDARDS = "cta-teacher-standards-select-standards",
  CTA_TEACHER_STANDARDS_TITLE = "cta-teacher-standards-title",
  CTA_TEACHER_STANDARDS_UPLOAD = "cta-teacher-standards-upload",
  CTA_TEACHERGPT_CHAT_CLEAR = "cta-teachergpt-chat-clear",
  CTA_TEACHERGPT_CHAT_INPUT = "cta-teachergpt-chat-input",
  CTA_TEACHERGPT_CHAT_KDCHECK_SAVE = "cta-teachergpt-chat-kdcheck-save",
  CTA_TEACHERGPT_CHAT_LESPLAN_PRINT = "cta-teachergpt-chat-lesplan-print",
  CTA_TEACHERGPT_CHAT_LESPLAN_USE = "cta-teachergpt-chat-lesplan-use",
  CTA_TEACHERGPT_CHAT_RECOMMENDATION_USE = "cta-teachergpt-chat-recommendation-use",
  CTA_TEACHERGPT_CHAT_RECOMMENDATION_OPEN = "cta-teachergpt-chat-recommendation-open",
  CTA_TEACHERGPT_CHAT_RECOMMENDATION_OPEN_URL = "cta-teachergpt-chat-recommendation-open-url",
  CTA_TEACHERGPT_CHAT_SCOPE_ALL = "cta-teachergpt-chat-scope-all",
  CTA_TEACHERGPT_CHAT_SCOPE_MATERIALS = "cta-teachergpt-chat-scope-materials",
  CTA_TEACHERGPT_CHAT_SCOPE_MES = "cta-teachergpt-chat-scope-mes",
  CTA_TEACHERGPT_CHAT_SECTION_DISCUSSION = "cta-teachergpt-chat-section-discussion",
  CTA_TEACHERGPT_CHAT_SECTION_GROUP_WORK = "cta-teachergpt-chat-section-group-work",
  CTA_TEACHERGPT_CHAT_SECTION_KD_CHECK = "cta-teachergpt-chat-section-kd-check",
  CTA_TEACHERGPT_CHAT_SECTION_QUICK_START = "cta-teachergpt-chat-section-quick-start",
  CTA_TEACHERGPT_CHAT_SECTION_TEACHER_SCRIPT = "cta-teachergpt-chat-section-teacher-script",
  CTA_TEACHERGPT_CHAT_SEND = "cta-teachergpt-chat-send",
  CTA_TEACHERGPT_CHAT_SETTINGS_MATERIAL_REFRESH = "cta-teachergpt-chat-settings-material-refresh",
  CTA_TEACHERGPT_CHAT_SETTINGS_MATERIAL_SELECT = "cta-teachergpt-chat-settings-material-select",
  CTA_TEACHERGPT_CHAT_SETTINGS_SCOPE = "cta-teachergpt-chat-settings-scope",
  CTA_TEACHERGPT_CHAT_SETTINGS_TOGGLE = "cta-teachergpt-chat-settings-toggle",
  CTA_TEACHERGPT_CHAT_SUGGESTION_B1_K1_W2 = "cta-teachergpt-chat-suggestion-b1-k1-w2",
  CTA_TEACHERGPT_CHAT_SUGGESTION_B1_K1_W3 = "cta-teachergpt-chat-suggestion-b1-k1-w3",
  CTA_TEACHERGPT_CHAT_SUGGESTION_B1_K1_W5 = "cta-teachergpt-chat-suggestion-b1-k1-w5",
  CTA_TEACHERGPT_CHAT_SUGGESTION_B1_K2_W2 = "cta-teachergpt-chat-suggestion-b1-k2-w2",
  CTA_TEACHERGPT_CHAT_SUGGESTION_B1_K3_W2 = "cta-teachergpt-chat-suggestion-b1-k3-w2",
  CTA_TEACHERGPT_CHAT_TAB_LESPLAN = "cta-teachergpt-chat-tab-lesplan",
  CTA_TEACHERGPT_CHAT_TAB_MATERIALS = "cta-teachergpt-chat-tab-materials",
  CTA_TEACHERGPT_CHAT_TAB_SOURCES = "cta-teachergpt-chat-tab-sources",
  CTA_TEACHERGPT_MES_INDEX_DOCS = "cta-teachergpt-mes-index-docs",
  CTA_TEACHERGPT_MES_INDEX_RUN = "cta-teachergpt-mes-index-run",
  CTA_TEACHERGPT_MES_LIMIT = "cta-teachergpt-mes-limit",
  CTA_TEACHERGPT_MES_QUERY = "cta-teachergpt-mes-query",
  CTA_TEACHERGPT_MES_SEARCH = "cta-teachergpt-mes-search",
  CTA_UPDATE_GOAL = "cta-update-goal",
  CTA_VIEW_ACHIEVEMENT = "cta-view-achievement",
  CTA_VIEW_CHILD_GOALS = "cta-view-child-goals",
  CTA_VIEW_CHILD_PROGRESS = "cta-view-child-progress",
  CTA_VIEW_TIMELINE_EVENT = "cta-view-timeline-event",
  CTA_WYSIWYG_BACK_TO_SELECT = "cta-wysiwyg-back-to-select",
  CTA_WYSIWYG_EXPLANATION_AI_IMAGE = "cta-wysiwyg-explanation-ai-image",
  CTA_WYSIWYG_EXPLANATION_AI_REWRITE = "cta-wysiwyg-explanation-ai-rewrite",
  CTA_WYSIWYG_EXPLANATION_EDIT = "cta-wysiwyg-explanation-edit",
  CTA_WYSIWYG_EXPLANATION_UPLOAD_MEDIA = "cta-wysiwyg-explanation-upload-media",
  CTA_WYSIWYG_NAV_ITEM_0_0 = "cta-wysiwyg-nav-item-0-0",
  CTA_WYSIWYG_NAV_ITEM_0_1 = "cta-wysiwyg-nav-item-0-1",
  CTA_WYSIWYG_NAV_ITEM_0_2 = "cta-wysiwyg-nav-item-0-2",
  CTA_WYSIWYG_NAV_ITEM_0_3 = "cta-wysiwyg-nav-item-0-3",
  CTA_WYSIWYG_NAV_ITEM_0_4 = "cta-wysiwyg-nav-item-0-4",
  CTA_WYSIWYG_NAV_ITEM_0_5 = "cta-wysiwyg-nav-item-0-5",
  CTA_WYSIWYG_NAV_ITEM_1_0 = "cta-wysiwyg-nav-item-1-0",
  CTA_WYSIWYG_NAV_ITEM_1_1 = "cta-wysiwyg-nav-item-1-1",
  CTA_WYSIWYG_NEXT = "cta-wysiwyg-next",
  CTA_WYSIWYG_OPTION_AI_IMAGE_0 = "cta-wysiwyg-option-ai-image-0",
  CTA_WYSIWYG_OPTION_AI_IMAGE_1 = "cta-wysiwyg-option-ai-image-1",
  CTA_WYSIWYG_OPTION_AI_IMAGE_2 = "cta-wysiwyg-option-ai-image-2",
  CTA_WYSIWYG_OPTION_AI_IMAGE_3 = "cta-wysiwyg-option-ai-image-3",
  CTA_WYSIWYG_OPTION_AI_REWRITE_0 = "cta-wysiwyg-option-ai-rewrite-0",
  CTA_WYSIWYG_OPTION_AI_REWRITE_1 = "cta-wysiwyg-option-ai-rewrite-1",
  CTA_WYSIWYG_OPTION_AI_REWRITE_2 = "cta-wysiwyg-option-ai-rewrite-2",
  CTA_WYSIWYG_OPTION_AI_REWRITE_3 = "cta-wysiwyg-option-ai-rewrite-3",
  CTA_WYSIWYG_OPTION_EDIT_0 = "cta-wysiwyg-option-edit-0",
  CTA_WYSIWYG_OPTION_EDIT_1 = "cta-wysiwyg-option-edit-1",
  CTA_WYSIWYG_OPTION_EDIT_2 = "cta-wysiwyg-option-edit-2",
  CTA_WYSIWYG_OPTION_EDIT_3 = "cta-wysiwyg-option-edit-3",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_0 = "cta-wysiwyg-option-media-upload-0",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_1 = "cta-wysiwyg-option-media-upload-1",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_2 = "cta-wysiwyg-option-media-upload-2",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_3 = "cta-wysiwyg-option-media-upload-3",
  CTA_WYSIWYG_OPTION_SET_CORRECT_0 = "cta-wysiwyg-option-set-correct-0",
  CTA_WYSIWYG_OPTION_SET_CORRECT_1 = "cta-wysiwyg-option-set-correct-1",
  CTA_WYSIWYG_OPTION_SET_CORRECT_2 = "cta-wysiwyg-option-set-correct-2",
  CTA_WYSIWYG_OPTION_SET_CORRECT_3 = "cta-wysiwyg-option-set-correct-3",
  CTA_WYSIWYG_PREV = "cta-wysiwyg-prev",
  CTA_WYSIWYG_RETRY_LOAD = "cta-wysiwyg-retry-load",
  CTA_WYSIWYG_SAVE = "cta-wysiwyg-save",
  CTA_WYSIWYG_STEM_AI_IMAGE = "cta-wysiwyg-stem-ai-image",
  CTA_WYSIWYG_STEM_AI_REWRITE = "cta-wysiwyg-stem-ai-rewrite",
  CTA_WYSIWYG_STEM_EDIT = "cta-wysiwyg-stem-edit",
  CTA_WYSIWYG_STEM_UPLOAD_MEDIA = "cta-wysiwyg-stem-upload-media",
  NAV_ADMIN = "nav-admin",
  NAV_KIDS = "nav-kids",
  NAV_PARENTS = "nav-parents",
  NAV_SCHOOLS = "nav-schools",
}

export type CtaIdType = (typeof CtaId)[keyof typeof CtaId];


export const CTA_IDS = {
  CTA_ADD_STUDENT: "cta-add-student",
  CTA_ADMIN_BOOK_BACK: "cta-admin-book-back",
  CTA_ADMIN_BOOK_REFRESH: "cta-admin-book-refresh",
  CTA_ADMIN_BOOKMISSING_ARTIFACT_OPEN: "cta-admin-bookmissing-artifact-open",
  CTA_ADMIN_BOOKMISSING_BACK: "cta-admin-bookmissing-back",
  CTA_ADMIN_BOOKMISSING_BOOK_SELECT: "cta-admin-bookmissing-book-select",
  CTA_ADMIN_BOOKMISSING_OPEN_PDF: "cta-admin-bookmissing-open-pdf",
  CTA_ADMIN_BOOKMISSING_REFRESH: "cta-admin-bookmissing-refresh",
  CTA_ADMIN_BOOKMISSING_RERENDER: "cta-admin-bookmissing-rerender",
  CTA_ADMIN_BOOKMISSING_RUN_SELECT: "cta-admin-bookmissing-run-select",
  CTA_ADMIN_BOOKRUN_BACK: "cta-admin-bookrun-back",
  CTA_ADMIN_BOOKRUN_MISSING_AI_GENERATE: "cta-admin-bookrun-missing-ai-generate",
  CTA_ADMIN_BOOKRUN_MISSING_REFRESH: "cta-admin-bookrun-missing-refresh",
  CTA_ADMIN_BOOKRUN_MISSING_UPLOAD: "cta-admin-bookrun-missing-upload",
  CTA_ADMIN_BOOKRUN_REFRESH: "cta-admin-bookrun-refresh",
  CTA_ADMIN_BOOKS_INGEST: "cta-admin-books-ingest",
  CTA_ADMIN_BOOKS_INGEST_BOOKID: "cta-admin-books-ingest-bookid",
  CTA_ADMIN_BOOKS_INGEST_CANONICAL_FILE: "cta-admin-books-ingest-canonical-file",
  CTA_ADMIN_BOOKS_INGEST_FIGURES_FILE: "cta-admin-books-ingest-figures-file",
  CTA_ADMIN_BOOKS_INGEST_LEVEL: "cta-admin-books-ingest-level",
  CTA_ADMIN_BOOKS_INGEST_SOURCE: "cta-admin-books-ingest-source",
  CTA_ADMIN_BOOKS_INGEST_TITLE: "cta-admin-books-ingest-title",
  CTA_ADMIN_BOOKS_INGEST_TOKENS_FILE: "cta-admin-books-ingest-tokens-file",
  CTA_ADMIN_BOOKS_REFRESH: "cta-admin-books-refresh",
  CTA_ADMIN_BOOKVERSION_ALLOW_MISSING_IMAGES: "cta-admin-bookversion-allow-missing-images",
  CTA_ADMIN_BOOKVERSION_BACK: "cta-admin-bookversion-back",
  CTA_ADMIN_BOOKVERSION_BOOKGEN_PRO: "cta-admin-bookversion-bookgen-pro",
  CTA_ADMIN_BOOKVERSION_CHAPTERINDEX: "cta-admin-bookversion-chapterindex",
  CTA_ADMIN_BOOKVERSION_CREATE_OVERLAY: "cta-admin-bookversion-create-overlay",
  CTA_ADMIN_BOOKVERSION_ENQUEUE_BOOK: "cta-admin-bookversion-enqueue-book",
  CTA_ADMIN_BOOKVERSION_ENQUEUE_CHAPTER: "cta-admin-bookversion-enqueue-chapter",
  CTA_ADMIN_BOOKVERSION_EXPORT_COURSEID: "cta-admin-bookversion-export-courseid",
  CTA_ADMIN_BOOKVERSION_EXPORT_STUDYTEXTS: "cta-admin-bookversion-export-studytexts",
  CTA_ADMIN_BOOKVERSION_NEW_OVERLAY_LABEL: "cta-admin-bookversion-new-overlay-label",
  CTA_ADMIN_BOOKVERSION_OVERLAYID: "cta-admin-bookversion-overlayid",
  CTA_ADMIN_BOOKVERSION_REFRESH: "cta-admin-bookversion-refresh",
  CTA_ADMIN_BOOKVERSION_RENDER_PROVIDER: "cta-admin-bookversion-render-provider",
  CTA_ADMIN_LIBRARY_COURSE_BACK: "cta-admin-library-course-back",
  CTA_ADMIN_LIBRARY_COURSES_FORMAT: "cta-admin-library-courses-format",
  CTA_ADMIN_LIBRARY_COURSES_NEXT: "cta-admin-library-courses-next",
  CTA_ADMIN_LIBRARY_COURSES_OPEN: "cta-admin-library-courses-open",
  CTA_ADMIN_LIBRARY_COURSES_PAGE_SIZE: "cta-admin-library-courses-page-size",
  CTA_ADMIN_LIBRARY_COURSES_PREV: "cta-admin-library-courses-prev",
  CTA_ADMIN_LIBRARY_COURSES_REFRESH: "cta-admin-library-courses-refresh",
  CTA_ADMIN_LIBRARY_COURSES_SEARCH: "cta-admin-library-courses-search",
  CTA_ADMIN_OVERLAY_BACK: "cta-admin-overlay-back",
  CTA_ADMIN_OVERLAY_CLEAR_SELECTION: "cta-admin-overlay-clear-selection",
  CTA_ADMIN_OVERLAY_DERIVED_COURSEID: "cta-admin-overlay-derived-courseid",
  CTA_ADMIN_OVERLAY_GENERATE_EXERCISES: "cta-admin-overlay-generate-exercises",
  CTA_ADMIN_OVERLAY_ONLY_EDITED: "cta-admin-overlay-only-edited",
  CTA_ADMIN_OVERLAY_REFRESH: "cta-admin-overlay-refresh",
  CTA_ADMIN_OVERLAY_SAVE: "cta-admin-overlay-save",
  CTA_ADMIN_OVERLAY_SEARCH: "cta-admin-overlay-search",
  CTA_ADMIN_OVERLAY_SELECT_ALL: "cta-admin-overlay-select-all",
  CTA_BOOKGEN_BACK: "cta-bookgen-back",
  CTA_BOOKGEN_BOOKID: "cta-bookgen-bookid",
  CTA_BOOKGEN_CHAPTERS: "cta-bookgen-chapters",
  CTA_BOOKGEN_CLONE_BOOK: "cta-bookgen-clone-book",
  CTA_BOOKGEN_DOCS: "cta-bookgen-docs",
  CTA_BOOKGEN_HISTORY: "cta-bookgen-history",
  CTA_BOOKGEN_IMAGES_FILTER_ALL: "cta-bookgen-images-filter-all",
  CTA_BOOKGEN_IMAGES_FILTER_CHAPTER: "cta-bookgen-images-filter-chapter",
  CTA_BOOKGEN_IMAGES_FILTER_COMPLETE: "cta-bookgen-images-filter-complete",
  CTA_BOOKGEN_IMAGES_FILTER_PENDING: "cta-bookgen-images-filter-pending",
  CTA_BOOKGEN_IMAGES_GENERATE_ALL: "cta-bookgen-images-generate-all",
  CTA_BOOKGEN_IMAGES_RENDER_PREVIEW: "cta-bookgen-images-render-preview",
  CTA_BOOKGEN_IMG_GENERATE_1: "cta-bookgen-img-generate-1",
  CTA_BOOKGEN_IMG_GENERATE_2: "cta-bookgen-img-generate-2",
  CTA_BOOKGEN_IMG_GENERATE_4: "cta-bookgen-img-generate-4",
  CTA_BOOKGEN_IMG_REMOVE_3: "cta-bookgen-img-remove-3",
  CTA_BOOKGEN_IMG_REPLACE_3: "cta-bookgen-img-replace-3",
  CTA_BOOKGEN_IMG_UPLOAD_1: "cta-bookgen-img-upload-1",
  CTA_BOOKGEN_IMG_UPLOAD_2: "cta-bookgen-img-upload-2",
  CTA_BOOKGEN_IMG_UPLOAD_4: "cta-bookgen-img-upload-4",
  CTA_BOOKGEN_IMPORT_SKELETON: "cta-bookgen-import-skeleton",
  CTA_BOOKGEN_LANGUAGE: "cta-bookgen-language",
  CTA_BOOKGEN_LEVEL: "cta-bookgen-level",
  CTA_BOOKGEN_OPEN_EDITOR: "cta-bookgen-open-editor",
  CTA_BOOKGEN_PACK_BUSINESS: "cta-bookgen-pack-business",
  CTA_BOOKGEN_PACK_GENERAL: "cta-bookgen-pack-general",
  CTA_BOOKGEN_PACK_MEDICAL: "cta-bookgen-pack-medical",
  CTA_BOOKGEN_PACK_TECHNICAL: "cta-bookgen-pack-technical",
  CTA_BOOKGEN_PRESET_BALANCED: "cta-bookgen-preset-balanced",
  CTA_BOOKGEN_PRESET_CUSTOM: "cta-bookgen-preset-custom",
  CTA_BOOKGEN_PRESET_FAST: "cta-bookgen-preset-fast",
  CTA_BOOKGEN_PRESET_QUALITY: "cta-bookgen-preset-quality",
  CTA_BOOKGEN_PREVIEW_JSON: "cta-bookgen-preview-json",
  CTA_BOOKGEN_PREVIEW_OUTLINE: "cta-bookgen-preview-outline",
  CTA_BOOKGEN_RENDER_FINAL: "cta-bookgen-render-final",
  CTA_BOOKGEN_SAVE_DRAFT: "cta-bookgen-save-draft",
  CTA_BOOKGEN_SKELETON_CLAUDE: "cta-bookgen-skeleton-claude",
  CTA_BOOKGEN_SKELETON_GPT4O: "cta-bookgen-skeleton-gpt4o",
  CTA_BOOKGEN_STAGE_COMPILE_CONFIG: "cta-bookgen-stage-compile-config",
  CTA_BOOKGEN_STAGE_IMAGES_CONFIG: "cta-bookgen-stage-images-config",
  CTA_BOOKGEN_STAGE_SKELETON_CONFIG: "cta-bookgen-stage-skeleton-config",
  CTA_BOOKGEN_STAGE_VALIDATE_CONFIG: "cta-bookgen-stage-validate-config",
  CTA_BOOKGEN_STAGE_WRITE_CONFIG: "cta-bookgen-stage-write-config",
  CTA_BOOKGEN_START: "cta-bookgen-start",
  CTA_BOOKGEN_TOPIC: "cta-bookgen-topic",
  CTA_BOOKGEN_VALIDATE_CLAUDE: "cta-bookgen-validate-claude",
  CTA_BOOKGEN_VALIDATE_GPT4O: "cta-bookgen-validate-gpt4o",
  CTA_BOOKGEN_WRITE_CLAUDE_OPUS: "cta-bookgen-write-claude-opus",
  CTA_BOOKGEN_WRITE_CLAUDE_SONNET: "cta-bookgen-write-claude-sonnet",
  CTA_BOOKGEN_WRITE_GPT4O: "cta-bookgen-write-gpt4o",
  CTA_BOOKGEN_WRITE_O1: "cta-bookgen-write-o1",
  CTA_BOOKMONITOR_BOOK_SELECT: "cta-bookmonitor-book-select",
  CTA_BOOKMONITOR_CHAPTER_CELL: "cta-bookmonitor-chapter-cell",
  CTA_BOOKSTUDIO_ADD_BOOK: "cta-bookstudio-add-book",
  CTA_BOOKSTUDIO_BACK_TO_BOOK: "cta-bookstudio-back-to-book",
  CTA_BOOKSTUDIO_BACK_TO_LIBRARY: "cta-bookstudio-back-to-library",
  CTA_BOOKSTUDIO_BOOK_ARCHIVE: "cta-bookstudio-book-archive",
  CTA_BOOKSTUDIO_BOOK_EXPORT: "cta-bookstudio-book-export",
  CTA_BOOKSTUDIO_BOOK_MISSING_IMAGES: "cta-bookstudio-book-missing-images",
  CTA_BOOKSTUDIO_BOOK_REFRESH: "cta-bookstudio-book-refresh",
  CTA_BOOKSTUDIO_BOOK_RENDER: "cta-bookstudio-book-render",
  CTA_BOOKSTUDIO_BOOK_RUNS: "cta-bookstudio-book-runs",
  CTA_BOOKSTUDIO_BOOK_VERSIONS: "cta-bookstudio-book-versions",
  CTA_BOOKSTUDIO_CHAPTER_AI_REWRITE_ALL: "cta-bookstudio-chapter-ai-rewrite-all",
  CTA_BOOKSTUDIO_CHAPTER_DISCARD: "cta-bookstudio-chapter-discard",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_0: "cta-bookstudio-chapter-edit-0",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_1: "cta-bookstudio-chapter-edit-1",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_2: "cta-bookstudio-chapter-edit-2",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_3: "cta-bookstudio-chapter-edit-3",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_4: "cta-bookstudio-chapter-edit-4",
  CTA_BOOKSTUDIO_CHAPTER_EDIT_5: "cta-bookstudio-chapter-edit-5",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_0: "cta-bookstudio-chapter-opener-0",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_1: "cta-bookstudio-chapter-opener-1",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_2: "cta-bookstudio-chapter-opener-2",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_3: "cta-bookstudio-chapter-opener-3",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_4: "cta-bookstudio-chapter-opener-4",
  CTA_BOOKSTUDIO_CHAPTER_OPENER_5: "cta-bookstudio-chapter-opener-5",
  CTA_BOOKSTUDIO_CHAPTER_SAVE: "cta-bookstudio-chapter-save",
  CTA_BOOKSTUDIO_COVER_AI: "cta-bookstudio-cover-ai",
  CTA_BOOKSTUDIO_COVER_UPLOAD: "cta-bookstudio-cover-upload",
  CTA_BOOKSTUDIO_DIFF_TOGGLE_SPLIT: "cta-bookstudio-diff-toggle-split",
  CTA_BOOKSTUDIO_DIFF_TOGGLE_UNIFIED: "cta-bookstudio-diff-toggle-unified",
  CTA_BOOKSTUDIO_FILTER_ALL: "cta-bookstudio-filter-all",
  CTA_BOOKSTUDIO_FILTER_DRAFT: "cta-bookstudio-filter-draft",
  CTA_BOOKSTUDIO_FILTER_N3: "cta-bookstudio-filter-n3",
  CTA_BOOKSTUDIO_FILTER_N4: "cta-bookstudio-filter-n4",
  CTA_BOOKSTUDIO_FILTER_PUBLISHED: "cta-bookstudio-filter-published",
  CTA_BOOKSTUDIO_GENERATE: "cta-bookstudio-generate",
  CTA_BOOKSTUDIO_INGEST_NEW: "cta-bookstudio-ingest-new",
  CTA_BOOKSTUDIO_INSPECTOR_AI_REWRITE: "cta-bookstudio-inspector-ai-rewrite",
  CTA_BOOKSTUDIO_INSPECTOR_CLEAR_SELECTION: "cta-bookstudio-inspector-clear-selection",
  CTA_BOOKSTUDIO_INSPECTOR_HTML: "cta-bookstudio-inspector-html",
  CTA_BOOKSTUDIO_INSPECTOR_REVERT: "cta-bookstudio-inspector-revert",
  CTA_BOOKSTUDIO_NAV_SECTION_0: "cta-bookstudio-nav-section-0",
  CTA_BOOKSTUDIO_NAV_SECTION_1: "cta-bookstudio-nav-section-1",
  CTA_BOOKSTUDIO_NAV_SECTION_2: "cta-bookstudio-nav-section-2",
  CTA_BOOKSTUDIO_NAV_SECTION_3: "cta-bookstudio-nav-section-3",
  CTA_BOOKSTUDIO_NAV_SECTION_4: "cta-bookstudio-nav-section-4",
  CTA_BOOKSTUDIO_OPEN_ANATOMIE_N3: "cta-bookstudio-open-anatomie_n3",
  CTA_BOOKSTUDIO_OPEN_FARMACOLOGIE_N4: "cta-bookstudio-open-farmacologie_n4",
  CTA_BOOKSTUDIO_OPEN_PATHOLOGIE_N4: "cta-bookstudio-open-pathologie_n4",
  CTA_BOOKSTUDIO_OPEN_PSYCHIATRIE_N3: "cta-bookstudio-open-psychiatrie_n3",
  CTA_BOOKSTUDIO_OPEN_VERPLEEGKUNDE_N4: "cta-bookstudio-open-verpleegkunde_n4",
  CTA_BOOKSTUDIO_PARA_AI_REWRITE_0: "cta-bookstudio-para-ai-rewrite-0",
  CTA_BOOKSTUDIO_PARA_AI_REWRITE_1: "cta-bookstudio-para-ai-rewrite-1",
  CTA_BOOKSTUDIO_PARA_AI_REWRITE_2: "cta-bookstudio-para-ai-rewrite-2",
  CTA_BOOKSTUDIO_PARA_EDIT_0: "cta-bookstudio-para-edit-0",
  CTA_BOOKSTUDIO_PARA_EDIT_2: "cta-bookstudio-para-edit-2",
  CTA_BOOKSTUDIO_PARA_IMAGE_AI_1: "cta-bookstudio-para-image-ai-1",
  CTA_BOOKSTUDIO_PARA_IMAGE_REMOVE_2: "cta-bookstudio-para-image-remove-2",
  CTA_BOOKSTUDIO_PARA_IMAGE_REPLACE_2: "cta-bookstudio-para-image-replace-2",
  CTA_BOOKSTUDIO_PARA_IMAGE_UPLOAD_1: "cta-bookstudio-para-image-upload-1",
  CTA_BOOKSTUDIO_PARA_MICROHEAD_0: "cta-bookstudio-para-microhead-0",
  CTA_BOOKSTUDIO_PARA_REVERT_0: "cta-bookstudio-para-revert-0",
  CTA_BOOKSTUDIO_PARA_REVERT_1: "cta-bookstudio-para-revert-1",
  CTA_BOOKSTUDIO_PARA_REVERT_2: "cta-bookstudio-para-revert-2",
  CTA_BOOKSTUDIO_PARA_SAVE_1: "cta-bookstudio-para-save-1",
  CTA_BOOKSTUDIO_PARA_SELECT_REWRITE_0: "cta-bookstudio-para-select-rewrite-0",
  CTA_BOOKSTUDIO_PARA_SUGGEST_MICROHEAD_0: "cta-bookstudio-para-suggest-microhead-0",
  CTA_BOOKSTUDIO_PARA_TEXT_1: "cta-bookstudio-para-text-1",
  CTA_BOOKSTUDIO_PROOF_OPEN: "cta-bookstudio-proof-open",
  CTA_BOOKSTUDIO_PROOF_OPEN_RUN: "cta-bookstudio-proof-open-run",
  CTA_BOOKSTUDIO_PROOF_REFRESH: "cta-bookstudio-proof-refresh",
  CTA_BOOKSTUDIO_REFRESH: "cta-bookstudio-refresh",
  CTA_BOOKSTUDIO_REVERT_TO_V2: "cta-bookstudio-revert-to-v2",
  CTA_BOOKSTUDIO_REWRITE_ALL_BOOK: "cta-bookstudio-rewrite-all-book",
  CTA_BOOKSTUDIO_SEARCH: "cta-bookstudio-search",
  CTA_BOOKSTUDIO_SECTION_ADD_IMAGE: "cta-bookstudio-section-add-image",
  CTA_BOOKSTUDIO_SECTION_AI_REWRITE: "cta-bookstudio-section-ai-rewrite",
  CTA_BOOKSTUDIO_VERSION_COMPARE: "cta-bookstudio-version-compare",
  CTA_BOOKSTUDIO_VERSION_DIFF_1: "cta-bookstudio-version-diff-1",
  CTA_BOOKSTUDIO_VERSION_DIFF_2: "cta-bookstudio-version-diff-2",
  CTA_BOOKSTUDIO_VERSION_ITEM_1: "cta-bookstudio-version-item-1",
  CTA_BOOKSTUDIO_VERSION_ITEM_2: "cta-bookstudio-version-item-2",
  CTA_BOOKSTUDIO_VERSION_ITEM_3: "cta-bookstudio-version-item-3",
  CTA_BOOKSTUDIO_VERSION_PUBLISH: "cta-bookstudio-version-publish",
  CTA_BOOKSTUDIO_VERSION_REVERT_1: "cta-bookstudio-version-revert-1",
  CTA_BOOKSTUDIO_VERSION_REVERT_2: "cta-bookstudio-version-revert-2",
  CTA_BOOKSTUDIO_VERSION_SELECT_1: "cta-bookstudio-version-select-1",
  CTA_BOOKSTUDIO_VERSION_SELECT_2: "cta-bookstudio-version-select-2",
  CTA_BOOKSTUDIO_VERSIONS_BACK: "cta-bookstudio-versions-back",
  CTA_BOOKSTUDIO_VERSIONS_EXPORT: "cta-bookstudio-versions-export",
  CTA_BOOKSTUDIO_VIEW_EDIT: "cta-bookstudio-view-edit",
  CTA_BOOKSTUDIO_VIEW_PROOF: "cta-bookstudio-view-proof",
  CTA_BOOKSTUDIO_WYSIWYG_ZOOM: "cta-bookstudio-wysiwyg-zoom",
  CTA_CANCEL: "cta-cancel",
  CTA_COURSEEDITOR_CLOSE: "cta-courseeditor-close",
  CTA_COURSEEDITOR_COMMAND_ARCHIVE: "cta-courseeditor-command-archive",
  CTA_COURSEEDITOR_COMMAND_AUDIT_VARIANTS: "cta-courseeditor-command-audit-variants",
  CTA_COURSEEDITOR_COMMAND_COPILOT_ENRICH: "cta-courseeditor-command-copilot-enrich",
  CTA_COURSEEDITOR_COMMAND_COPILOT_VARIANTS: "cta-courseeditor-command-copilot-variants",
  CTA_COURSEEDITOR_COMMAND_DELETE: "cta-courseeditor-command-delete",
  CTA_COURSEEDITOR_COMMAND_DISCARD: "cta-courseeditor-command-discard",
  CTA_COURSEEDITOR_COMMAND_GENERATE_MISSING_VARIANTS: "cta-courseeditor-command-generate-missing-variants",
  CTA_COURSEEDITOR_COMMAND_LOCALIZE: "cta-courseeditor-command-localize",
  CTA_COURSEEDITOR_COMMAND_PALETTE: "cta-courseeditor-command-palette",
  CTA_COURSEEDITOR_COMMAND_PUBLISH: "cta-courseeditor-command-publish",
  CTA_COURSEEDITOR_COMMAND_REPAIR: "cta-courseeditor-command-repair",
  CTA_COURSEEDITOR_COMMAND_SAVE: "cta-courseeditor-command-save",
  CTA_COURSEEDITOR_DISCARD: "cta-courseeditor-discard",
  CTA_COURSEEDITOR_EDITOR_TAB_EXERCISES: "cta-courseeditor-editor-tab-exercises",
  CTA_COURSEEDITOR_EDITOR_TAB_EXPLANATION: "cta-courseeditor-editor-tab-explanation",
  CTA_COURSEEDITOR_EDITOR_TAB_OPTIONS: "cta-courseeditor-editor-tab-options",
  CTA_COURSEEDITOR_EDITOR_TAB_STEM: "cta-courseeditor-editor-tab-stem",
  CTA_COURSEEDITOR_EXERCISES_GENERATE: "cta-courseeditor-exercises-generate",
  CTA_COURSEEDITOR_EXPLANATION_AI_REWRITE: "cta-courseeditor-explanation-ai-rewrite",
  CTA_COURSEEDITOR_FAB_ADD_IMAGE_AI: "cta-courseeditor-fab-add-image-ai",
  CTA_COURSEEDITOR_FAB_AI_REWRITE_STEM: "cta-courseeditor-fab-ai-rewrite-stem",
  CTA_COURSEEDITOR_FAB_GENERATE_EXERCISES: "cta-courseeditor-fab-generate-exercises",
  CTA_COURSEEDITOR_FAB_TOGGLE: "cta-courseeditor-fab-toggle",
  CTA_COURSEEDITOR_ITEM_ADD_IMAGE_AI: "cta-courseeditor-item-add-image-ai",
  CTA_COURSEEDITOR_ITEM_FIX_MISSING_IMAGES: "cta-courseeditor-item-fix-missing-images",
  CTA_COURSEEDITOR_MEDIA_FILTER_ALL: "cta-courseeditor-media-filter-all",
  CTA_COURSEEDITOR_MEDIA_FILTER_AUDIO: "cta-courseeditor-media-filter-audio",
  CTA_COURSEEDITOR_MEDIA_FILTER_IMAGES: "cta-courseeditor-media-filter-images",
  CTA_COURSEEDITOR_MEDIA_FILTER_VIDEO: "cta-courseeditor-media-filter-video",
  CTA_COURSEEDITOR_MEDIA_SELECT_0: "cta-courseeditor-media-select-0",
  CTA_COURSEEDITOR_MEDIA_SELECT_1: "cta-courseeditor-media-select-1",
  CTA_COURSEEDITOR_MEDIA_SELECT_2: "cta-courseeditor-media-select-2",
  CTA_COURSEEDITOR_MEDIA_SELECT_3: "cta-courseeditor-media-select-3",
  CTA_COURSEEDITOR_MEDIA_SELECT_4: "cta-courseeditor-media-select-4",
  CTA_COURSEEDITOR_MEDIA_SELECT_5: "cta-courseeditor-media-select-5",
  CTA_COURSEEDITOR_MEDIA_TOGGLE: "cta-courseeditor-media-toggle",
  CTA_COURSEEDITOR_MODE_SELECT: "cta-courseeditor-mode-select",
  CTA_COURSEEDITOR_NAV_ADD_GROUP: "cta-courseeditor-nav-add-group",
  CTA_COURSEEDITOR_NAV_COLLAPSE_ALL: "cta-courseeditor-nav-collapse-all",
  CTA_COURSEEDITOR_NAV_GROUP_TOGGLE_0: "cta-courseeditor-nav-group-toggle-0",
  CTA_COURSEEDITOR_NAV_GROUP_TOGGLE_1: "cta-courseeditor-nav-group-toggle-1",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_0: "cta-courseeditor-nav-item-select-0-0",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_1: "cta-courseeditor-nav-item-select-0-1",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_2: "cta-courseeditor-nav-item-select-0-2",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_3: "cta-courseeditor-nav-item-select-0-3",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_4: "cta-courseeditor-nav-item-select-0-4",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_5: "cta-courseeditor-nav-item-select-0-5",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_1_0: "cta-courseeditor-nav-item-select-1-0",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_1_1: "cta-courseeditor-nav-item-select-1-1",
  CTA_COURSEEDITOR_OPTION_0_ADD_MEDIA: "cta-courseeditor-option-0-add-media",
  CTA_COURSEEDITOR_OPTION_0_AI_REWRITE: "cta-courseeditor-option-0-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_1_ADD_MEDIA: "cta-courseeditor-option-1-add-media",
  CTA_COURSEEDITOR_OPTION_1_AI_REWRITE: "cta-courseeditor-option-1-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_2_ADD_MEDIA: "cta-courseeditor-option-2-add-media",
  CTA_COURSEEDITOR_OPTION_2_AI_REWRITE: "cta-courseeditor-option-2-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_3_ADD_MEDIA: "cta-courseeditor-option-3-add-media",
  CTA_COURSEEDITOR_OPTION_3_AI_REWRITE: "cta-courseeditor-option-3-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_ADD: "cta-courseeditor-option-add",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_1: "cta-courseeditor-option-mark-correct-1",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_2: "cta-courseeditor-option-mark-correct-2",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_3: "cta-courseeditor-option-mark-correct-3",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_0: "cta-courseeditor-preview-option-select-0",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_1: "cta-courseeditor-preview-option-select-1",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_2: "cta-courseeditor-preview-option-select-2",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_3: "cta-courseeditor-preview-option-select-3",
  CTA_COURSEEDITOR_PREVIEW_REFRESH: "cta-courseeditor-preview-refresh",
  CTA_COURSEEDITOR_PUBLISH: "cta-courseeditor-publish",
  CTA_COURSEEDITOR_SAVE: "cta-courseeditor-save",
  CTA_COURSEEDITOR_STEM_AI_REWRITE: "cta-courseeditor-stem-ai-rewrite",
  CTA_COURSEEDITOR_STEM_MEDIA_LIBRARY: "cta-courseeditor-stem-media-library",
  CTA_COURSEEDITOR_STEM_PREVIEW: "cta-courseeditor-stem-preview",
  CTA_COURSEEDITOR_STEM_UPLOAD_MEDIA: "cta-courseeditor-stem-upload-media",
  CTA_COURSEEDITOR_TAB_EXERCISES: "cta-courseeditor-tab-exercises",
  CTA_COURSEEDITOR_TAB_STUDYTEXTS: "cta-courseeditor-tab-studytexts",
  CTA_CREATE_CLASS: "cta-create-class",
  CTA_ECGEN_CLEAR: "cta-ecgen-clear",
  CTA_ECGEN_SAVE_TO_COURSE: "cta-ecgen-save-to-course",
  CTA_ECGEN_SCOPE_COURSE: "cta-ecgen-scope-course",
  CTA_ECGEN_SCOPE_SELECTED: "cta-ecgen-scope-selected",
  CTA_ECGEN_SCOPE_SINGLE: "cta-ecgen-scope-single",
  CTA_ECGEN_SELECT_ALL: "cta-ecgen-select-all",
  CTA_ECGEN_START: "cta-ecgen-start",
  CTA_GENERATE_ALL: "cta-generate-all",
  CTA_GENERATE_CHAPTER: "cta-generate-chapter",
  CTA_GENERATE_CLASS_CODE: "cta-generate-class-code",
  CTA_JOIN_CLASS: "cta-join-class",
  CTA_KW1C_KD_CODE: "cta-kw1c-kd-code",
  CTA_KW1C_LANGUAGE: "cta-kw1c-language",
  CTA_KW1C_OPEN_CLASSES: "cta-kw1c-open-classes",
  CTA_KW1C_OPEN_LESSON_KITS: "cta-kw1c-open-lesson-kits",
  CTA_KW1C_OPEN_MATERIALS: "cta-kw1c-open-materials",
  CTA_KW1C_OPEN_MES: "cta-kw1c-open-mes",
  CTA_KW1C_OPEN_RESULT: "cta-kw1c-open-result",
  CTA_KW1C_OPEN_STANDARDS: "cta-kw1c-open-standards",
  CTA_KW1C_OPEN_STUDENTS: "cta-kw1c-open-students",
  CTA_KW1C_OPEN_TEACHERGPT_CHAT: "cta-kw1c-open-teachergpt-chat",
  CTA_KW1C_QUERY: "cta-kw1c-query",
  CTA_KW1C_REFRESH: "cta-kw1c-refresh",
  CTA_KW1C_SEARCH: "cta-kw1c-search",
  CTA_KW1C_TO_TEACHER_DASHBOARD: "cta-kw1c-to-teacher-dashboard",
  CTA_KW1C_TYPE: "cta-kw1c-type",
  CTA_LINK_CHILD: "cta-link-child",
  CTA_PAUSE: "cta-pause",
  CTA_REMOVE_STUDENT: "cta-remove-student",
  CTA_RENDER_PDF: "cta-render-pdf",
  CTA_RESUME: "cta-resume",
  CTA_TEACHER_LESSON_KITS_AUTO_REPAIR: "cta-teacher-lesson-kits-auto-repair",
  CTA_TEACHER_LESSON_KITS_HTML: "cta-teacher-lesson-kits-html",
  CTA_TEACHER_LESSON_KITS_MODULE_ID: "cta-teacher-lesson-kits-module-id",
  CTA_TEACHER_LESSON_KITS_PROTOCOL: "cta-teacher-lesson-kits-protocol",
  CTA_TEACHER_LESSON_KITS_SUBMIT: "cta-teacher-lesson-kits-submit",
  CTA_TEACHER_MATERIALS_FILE: "cta-teacher-materials-file",
  CTA_TEACHER_MATERIALS_REFRESH: "cta-teacher-materials-refresh",
  CTA_TEACHER_MATERIALS_RESET: "cta-teacher-materials-reset",
  CTA_TEACHER_MATERIALS_TITLE: "cta-teacher-materials-title",
  CTA_TEACHER_MATERIALS_UPLOAD_AND_INGEST: "cta-teacher-materials-upload-and-ingest",
  CTA_TEACHER_STANDARDS_EXPORT: "cta-teacher-standards-export",
  CTA_TEACHER_STANDARDS_FILE: "cta-teacher-standards-file",
  CTA_TEACHER_STANDARDS_LOCALE: "cta-teacher-standards-locale",
  CTA_TEACHER_STANDARDS_MAP: "cta-teacher-standards-map",
  CTA_TEACHER_STANDARDS_REFRESH: "cta-teacher-standards-refresh",
  CTA_TEACHER_STANDARDS_RESET: "cta-teacher-standards-reset",
  CTA_TEACHER_STANDARDS_SELECT_MATERIAL: "cta-teacher-standards-select-material",
  CTA_TEACHER_STANDARDS_SELECT_STANDARDS: "cta-teacher-standards-select-standards",
  CTA_TEACHER_STANDARDS_TITLE: "cta-teacher-standards-title",
  CTA_TEACHER_STANDARDS_UPLOAD: "cta-teacher-standards-upload",
  CTA_TEACHERGPT_CHAT_CLEAR: "cta-teachergpt-chat-clear",
  CTA_TEACHERGPT_CHAT_INPUT: "cta-teachergpt-chat-input",
  CTA_TEACHERGPT_CHAT_KDCHECK_SAVE: "cta-teachergpt-chat-kdcheck-save",
  CTA_TEACHERGPT_CHAT_LESPLAN_PRINT: "cta-teachergpt-chat-lesplan-print",
  CTA_TEACHERGPT_CHAT_LESPLAN_USE: "cta-teachergpt-chat-lesplan-use",
  CTA_TEACHERGPT_CHAT_RECOMMENDATION_USE: "cta-teachergpt-chat-recommendation-use",
  CTA_TEACHERGPT_CHAT_RECOMMENDATION_OPEN: "cta-teachergpt-chat-recommendation-open",
  CTA_TEACHERGPT_CHAT_RECOMMENDATION_OPEN_URL: "cta-teachergpt-chat-recommendation-open-url",
  CTA_TEACHERGPT_CHAT_SCOPE_ALL: "cta-teachergpt-chat-scope-all",
  CTA_TEACHERGPT_CHAT_SCOPE_MATERIALS: "cta-teachergpt-chat-scope-materials",
  CTA_TEACHERGPT_CHAT_SCOPE_MES: "cta-teachergpt-chat-scope-mes",
  CTA_TEACHERGPT_CHAT_SECTION_DISCUSSION: "cta-teachergpt-chat-section-discussion",
  CTA_TEACHERGPT_CHAT_SECTION_GROUP_WORK: "cta-teachergpt-chat-section-group-work",
  CTA_TEACHERGPT_CHAT_SECTION_KD_CHECK: "cta-teachergpt-chat-section-kd-check",
  CTA_TEACHERGPT_CHAT_SECTION_QUICK_START: "cta-teachergpt-chat-section-quick-start",
  CTA_TEACHERGPT_CHAT_SECTION_TEACHER_SCRIPT: "cta-teachergpt-chat-section-teacher-script",
  CTA_TEACHERGPT_CHAT_SEND: "cta-teachergpt-chat-send",
  CTA_TEACHERGPT_CHAT_SETTINGS_MATERIAL_REFRESH: "cta-teachergpt-chat-settings-material-refresh",
  CTA_TEACHERGPT_CHAT_SETTINGS_MATERIAL_SELECT: "cta-teachergpt-chat-settings-material-select",
  CTA_TEACHERGPT_CHAT_SETTINGS_SCOPE: "cta-teachergpt-chat-settings-scope",
  CTA_TEACHERGPT_CHAT_SETTINGS_TOGGLE: "cta-teachergpt-chat-settings-toggle",
  CTA_TEACHERGPT_CHAT_SUGGESTION_B1_K1_W2: "cta-teachergpt-chat-suggestion-b1-k1-w2",
  CTA_TEACHERGPT_CHAT_SUGGESTION_B1_K1_W3: "cta-teachergpt-chat-suggestion-b1-k1-w3",
  CTA_TEACHERGPT_CHAT_SUGGESTION_B1_K1_W5: "cta-teachergpt-chat-suggestion-b1-k1-w5",
  CTA_TEACHERGPT_CHAT_SUGGESTION_B1_K2_W2: "cta-teachergpt-chat-suggestion-b1-k2-w2",
  CTA_TEACHERGPT_CHAT_SUGGESTION_B1_K3_W2: "cta-teachergpt-chat-suggestion-b1-k3-w2",
  CTA_TEACHERGPT_CHAT_TAB_LESPLAN: "cta-teachergpt-chat-tab-lesplan",
  CTA_TEACHERGPT_CHAT_TAB_MATERIALS: "cta-teachergpt-chat-tab-materials",
  CTA_TEACHERGPT_CHAT_TAB_SOURCES: "cta-teachergpt-chat-tab-sources",
  CTA_TEACHERGPT_MES_INDEX_DOCS: "cta-teachergpt-mes-index-docs",
  CTA_TEACHERGPT_MES_INDEX_RUN: "cta-teachergpt-mes-index-run",
  CTA_TEACHERGPT_MES_LIMIT: "cta-teachergpt-mes-limit",
  CTA_TEACHERGPT_MES_QUERY: "cta-teachergpt-mes-query",
  CTA_TEACHERGPT_MES_SEARCH: "cta-teachergpt-mes-search",
  CTA_UPDATE_GOAL: "cta-update-goal",
  CTA_VIEW_ACHIEVEMENT: "cta-view-achievement",
  CTA_VIEW_CHILD_GOALS: "cta-view-child-goals",
  CTA_VIEW_CHILD_PROGRESS: "cta-view-child-progress",
  CTA_VIEW_TIMELINE_EVENT: "cta-view-timeline-event",
  CTA_WYSIWYG_BACK_TO_SELECT: "cta-wysiwyg-back-to-select",
  CTA_WYSIWYG_EXPLANATION_AI_IMAGE: "cta-wysiwyg-explanation-ai-image",
  CTA_WYSIWYG_EXPLANATION_AI_REWRITE: "cta-wysiwyg-explanation-ai-rewrite",
  CTA_WYSIWYG_EXPLANATION_EDIT: "cta-wysiwyg-explanation-edit",
  CTA_WYSIWYG_EXPLANATION_UPLOAD_MEDIA: "cta-wysiwyg-explanation-upload-media",
  CTA_WYSIWYG_NAV_ITEM_0_0: "cta-wysiwyg-nav-item-0-0",
  CTA_WYSIWYG_NAV_ITEM_0_1: "cta-wysiwyg-nav-item-0-1",
  CTA_WYSIWYG_NAV_ITEM_0_2: "cta-wysiwyg-nav-item-0-2",
  CTA_WYSIWYG_NAV_ITEM_0_3: "cta-wysiwyg-nav-item-0-3",
  CTA_WYSIWYG_NAV_ITEM_0_4: "cta-wysiwyg-nav-item-0-4",
  CTA_WYSIWYG_NAV_ITEM_0_5: "cta-wysiwyg-nav-item-0-5",
  CTA_WYSIWYG_NAV_ITEM_1_0: "cta-wysiwyg-nav-item-1-0",
  CTA_WYSIWYG_NAV_ITEM_1_1: "cta-wysiwyg-nav-item-1-1",
  CTA_WYSIWYG_NEXT: "cta-wysiwyg-next",
  CTA_WYSIWYG_OPTION_AI_IMAGE_0: "cta-wysiwyg-option-ai-image-0",
  CTA_WYSIWYG_OPTION_AI_IMAGE_1: "cta-wysiwyg-option-ai-image-1",
  CTA_WYSIWYG_OPTION_AI_IMAGE_2: "cta-wysiwyg-option-ai-image-2",
  CTA_WYSIWYG_OPTION_AI_IMAGE_3: "cta-wysiwyg-option-ai-image-3",
  CTA_WYSIWYG_OPTION_AI_REWRITE_0: "cta-wysiwyg-option-ai-rewrite-0",
  CTA_WYSIWYG_OPTION_AI_REWRITE_1: "cta-wysiwyg-option-ai-rewrite-1",
  CTA_WYSIWYG_OPTION_AI_REWRITE_2: "cta-wysiwyg-option-ai-rewrite-2",
  CTA_WYSIWYG_OPTION_AI_REWRITE_3: "cta-wysiwyg-option-ai-rewrite-3",
  CTA_WYSIWYG_OPTION_EDIT_0: "cta-wysiwyg-option-edit-0",
  CTA_WYSIWYG_OPTION_EDIT_1: "cta-wysiwyg-option-edit-1",
  CTA_WYSIWYG_OPTION_EDIT_2: "cta-wysiwyg-option-edit-2",
  CTA_WYSIWYG_OPTION_EDIT_3: "cta-wysiwyg-option-edit-3",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_0: "cta-wysiwyg-option-media-upload-0",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_1: "cta-wysiwyg-option-media-upload-1",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_2: "cta-wysiwyg-option-media-upload-2",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_3: "cta-wysiwyg-option-media-upload-3",
  CTA_WYSIWYG_OPTION_SET_CORRECT_0: "cta-wysiwyg-option-set-correct-0",
  CTA_WYSIWYG_OPTION_SET_CORRECT_1: "cta-wysiwyg-option-set-correct-1",
  CTA_WYSIWYG_OPTION_SET_CORRECT_2: "cta-wysiwyg-option-set-correct-2",
  CTA_WYSIWYG_OPTION_SET_CORRECT_3: "cta-wysiwyg-option-set-correct-3",
  CTA_WYSIWYG_PREV: "cta-wysiwyg-prev",
  CTA_WYSIWYG_RETRY_LOAD: "cta-wysiwyg-retry-load",
  CTA_WYSIWYG_SAVE: "cta-wysiwyg-save",
  CTA_WYSIWYG_STEM_AI_IMAGE: "cta-wysiwyg-stem-ai-image",
  CTA_WYSIWYG_STEM_AI_REWRITE: "cta-wysiwyg-stem-ai-rewrite",
  CTA_WYSIWYG_STEM_EDIT: "cta-wysiwyg-stem-edit",
  CTA_WYSIWYG_STEM_UPLOAD_MEDIA: "cta-wysiwyg-stem-upload-media",
  NAV_ADMIN: "nav-admin",
  NAV_KIDS: "nav-kids",
  NAV_PARENTS: "nav-parents",
  NAV_SCHOOLS: "nav-schools"
} as const;

// Type guard
export function isValidCtaId(id: string): id is CtaIdType {
  return Object.values(CtaId).includes(id as CtaId);
}
