// ------------------------------------------------------------------
// ⚠️ AUTO-GENERATED FROM docs/mockups/coverage.json
// ------------------------------------------------------------------
// Run: npx ignite scaffold
// (or via npx tsx scripts/ignite.ts scaffold)

export enum CtaId {
  CTA_ADD_STUDENT = "cta-add-student",
  CTA_ADMIN_BOOK_BACK = "cta-admin-book-back",
  CTA_ADMIN_BOOK_REFRESH = "cta-admin-book-refresh",
  CTA_ADMIN_BOOKMISSING_ARTIFACT_OPEN = "cta-admin-bookmissing-artifact-open",
  CTA_ADMIN_BOOKMISSING_BACK = "cta-admin-bookmissing-back",
  CTA_ADMIN_BOOKMISSING_BOOK_SELECT = "cta-admin-bookmissing-book-select",
  CTA_ADMIN_BOOKMISSING_OPEN_PDF = "cta-admin-bookmissing-open-pdf",
  CTA_ADMIN_BOOKMISSING_REFRESH = "cta-admin-bookmissing-refresh",
  CTA_ADMIN_BOOKMISSING_RERENDER = "cta-admin-bookmissing-rerender",
  CTA_ADMIN_BOOKMISSING_RUN_SELECT = "cta-admin-bookmissing-run-select",
  CTA_ADMIN_BOOKRUN_BACK = "cta-admin-bookrun-back",
  CTA_ADMIN_BOOKRUN_MISSING_AI_GENERATE = "cta-admin-bookrun-missing-ai-generate",
  CTA_ADMIN_BOOKRUN_MISSING_REFRESH = "cta-admin-bookrun-missing-refresh",
  CTA_ADMIN_BOOKRUN_MISSING_UPLOAD = "cta-admin-bookrun-missing-upload",
  CTA_ADMIN_BOOKRUN_REFRESH = "cta-admin-bookrun-refresh",
  CTA_ADMIN_BOOKS_INGEST = "cta-admin-books-ingest",
  CTA_ADMIN_BOOKS_INGEST_BOOKID = "cta-admin-books-ingest-bookid",
  CTA_ADMIN_BOOKS_INGEST_CANONICAL_FILE = "cta-admin-books-ingest-canonical-file",
  CTA_ADMIN_BOOKS_INGEST_FIGURES_FILE = "cta-admin-books-ingest-figures-file",
  CTA_ADMIN_BOOKS_INGEST_LEVEL = "cta-admin-books-ingest-level",
  CTA_ADMIN_BOOKS_INGEST_SOURCE = "cta-admin-books-ingest-source",
  CTA_ADMIN_BOOKS_INGEST_TITLE = "cta-admin-books-ingest-title",
  CTA_ADMIN_BOOKS_INGEST_TOKENS_FILE = "cta-admin-books-ingest-tokens-file",
  CTA_ADMIN_BOOKS_REFRESH = "cta-admin-books-refresh",
  CTA_ADMIN_BOOKVERSION_ALLOW_MISSING_IMAGES = "cta-admin-bookversion-allow-missing-images",
  CTA_ADMIN_BOOKVERSION_BACK = "cta-admin-bookversion-back",
  CTA_ADMIN_BOOKVERSION_BOOKGEN_PRO = "cta-admin-bookversion-bookgen-pro",
  CTA_ADMIN_BOOKVERSION_CHAPTERINDEX = "cta-admin-bookversion-chapterindex",
  CTA_ADMIN_BOOKVERSION_CREATE_OVERLAY = "cta-admin-bookversion-create-overlay",
  CTA_ADMIN_BOOKVERSION_ENQUEUE_BOOK = "cta-admin-bookversion-enqueue-book",
  CTA_ADMIN_BOOKVERSION_ENQUEUE_CHAPTER = "cta-admin-bookversion-enqueue-chapter",
  CTA_ADMIN_BOOKVERSION_EXPORT_COURSEID = "cta-admin-bookversion-export-courseid",
  CTA_ADMIN_BOOKVERSION_EXPORT_STUDYTEXTS = "cta-admin-bookversion-export-studytexts",
  CTA_ADMIN_BOOKVERSION_NEW_OVERLAY_LABEL = "cta-admin-bookversion-new-overlay-label",
  CTA_ADMIN_BOOKVERSION_OVERLAYID = "cta-admin-bookversion-overlayid",
  CTA_ADMIN_BOOKVERSION_REFRESH = "cta-admin-bookversion-refresh",
  CTA_ADMIN_BOOKVERSION_RENDER_PROVIDER = "cta-admin-bookversion-render-provider",
  CTA_ADMIN_LIBRARY_COURSE_BACK = "cta-admin-library-course-back",
  CTA_ADMIN_LIBRARY_COURSES_FORMAT = "cta-admin-library-courses-format",
  CTA_ADMIN_LIBRARY_COURSES_NEXT = "cta-admin-library-courses-next",
  CTA_ADMIN_LIBRARY_COURSES_OPEN = "cta-admin-library-courses-open",
  CTA_ADMIN_LIBRARY_COURSES_PAGE_SIZE = "cta-admin-library-courses-page-size",
  CTA_ADMIN_LIBRARY_COURSES_PREV = "cta-admin-library-courses-prev",
  CTA_ADMIN_LIBRARY_COURSES_REFRESH = "cta-admin-library-courses-refresh",
  CTA_ADMIN_LIBRARY_COURSES_SEARCH = "cta-admin-library-courses-search",
  CTA_ADMIN_OVERLAY_BACK = "cta-admin-overlay-back",
  CTA_ADMIN_OVERLAY_CLEAR_SELECTION = "cta-admin-overlay-clear-selection",
  CTA_ADMIN_OVERLAY_DERIVED_COURSEID = "cta-admin-overlay-derived-courseid",
  CTA_ADMIN_OVERLAY_GENERATE_EXERCISES = "cta-admin-overlay-generate-exercises",
  CTA_ADMIN_OVERLAY_ONLY_EDITED = "cta-admin-overlay-only-edited",
  CTA_ADMIN_OVERLAY_REFRESH = "cta-admin-overlay-refresh",
  CTA_ADMIN_OVERLAY_SAVE = "cta-admin-overlay-save",
  CTA_ADMIN_OVERLAY_SEARCH = "cta-admin-overlay-search",
  CTA_ADMIN_OVERLAY_SELECT_ALL = "cta-admin-overlay-select-all",
  CTA_COURSEEDITOR_CLOSE = "cta-courseeditor-close",
  CTA_COURSEEDITOR_COMMAND_ARCHIVE = "cta-courseeditor-command-archive",
  CTA_COURSEEDITOR_COMMAND_AUDIT_VARIANTS = "cta-courseeditor-command-audit-variants",
  CTA_COURSEEDITOR_COMMAND_COPILOT_ENRICH = "cta-courseeditor-command-copilot-enrich",
  CTA_COURSEEDITOR_COMMAND_COPILOT_VARIANTS = "cta-courseeditor-command-copilot-variants",
  CTA_COURSEEDITOR_COMMAND_DELETE = "cta-courseeditor-command-delete",
  CTA_COURSEEDITOR_COMMAND_DISCARD = "cta-courseeditor-command-discard",
  CTA_COURSEEDITOR_COMMAND_GENERATE_MISSING_VARIANTS = "cta-courseeditor-command-generate-missing-variants",
  CTA_COURSEEDITOR_COMMAND_LOCALIZE = "cta-courseeditor-command-localize",
  CTA_COURSEEDITOR_COMMAND_PALETTE = "cta-courseeditor-command-palette",
  CTA_COURSEEDITOR_COMMAND_PUBLISH = "cta-courseeditor-command-publish",
  CTA_COURSEEDITOR_COMMAND_REPAIR = "cta-courseeditor-command-repair",
  CTA_COURSEEDITOR_COMMAND_SAVE = "cta-courseeditor-command-save",
  CTA_COURSEEDITOR_DISCARD = "cta-courseeditor-discard",
  CTA_COURSEEDITOR_EDITOR_TAB_EXERCISES = "cta-courseeditor-editor-tab-exercises",
  CTA_COURSEEDITOR_EDITOR_TAB_EXPLANATION = "cta-courseeditor-editor-tab-explanation",
  CTA_COURSEEDITOR_EDITOR_TAB_OPTIONS = "cta-courseeditor-editor-tab-options",
  CTA_COURSEEDITOR_EDITOR_TAB_STEM = "cta-courseeditor-editor-tab-stem",
  CTA_COURSEEDITOR_EXERCISES_GENERATE = "cta-courseeditor-exercises-generate",
  CTA_COURSEEDITOR_EXPLANATION_AI_REWRITE = "cta-courseeditor-explanation-ai-rewrite",
  CTA_COURSEEDITOR_FAB_ADD_IMAGE_AI = "cta-courseeditor-fab-add-image-ai",
  CTA_COURSEEDITOR_FAB_AI_REWRITE_STEM = "cta-courseeditor-fab-ai-rewrite-stem",
  CTA_COURSEEDITOR_FAB_GENERATE_EXERCISES = "cta-courseeditor-fab-generate-exercises",
  CTA_COURSEEDITOR_FAB_TOGGLE = "cta-courseeditor-fab-toggle",
  CTA_COURSEEDITOR_ITEM_ADD_IMAGE_AI = "cta-courseeditor-item-add-image-ai",
  CTA_COURSEEDITOR_ITEM_FIX_MISSING_IMAGES = "cta-courseeditor-item-fix-missing-images",
  CTA_COURSEEDITOR_MEDIA_FILTER_ALL = "cta-courseeditor-media-filter-all",
  CTA_COURSEEDITOR_MEDIA_FILTER_AUDIO = "cta-courseeditor-media-filter-audio",
  CTA_COURSEEDITOR_MEDIA_FILTER_IMAGES = "cta-courseeditor-media-filter-images",
  CTA_COURSEEDITOR_MEDIA_FILTER_VIDEO = "cta-courseeditor-media-filter-video",
  CTA_COURSEEDITOR_MEDIA_SELECT_0 = "cta-courseeditor-media-select-0",
  CTA_COURSEEDITOR_MEDIA_SELECT_1 = "cta-courseeditor-media-select-1",
  CTA_COURSEEDITOR_MEDIA_SELECT_2 = "cta-courseeditor-media-select-2",
  CTA_COURSEEDITOR_MEDIA_SELECT_3 = "cta-courseeditor-media-select-3",
  CTA_COURSEEDITOR_MEDIA_SELECT_4 = "cta-courseeditor-media-select-4",
  CTA_COURSEEDITOR_MEDIA_SELECT_5 = "cta-courseeditor-media-select-5",
  CTA_COURSEEDITOR_MEDIA_TOGGLE = "cta-courseeditor-media-toggle",
  CTA_COURSEEDITOR_MODE_SELECT = "cta-courseeditor-mode-select",
  CTA_COURSEEDITOR_NAV_ADD_GROUP = "cta-courseeditor-nav-add-group",
  CTA_COURSEEDITOR_NAV_COLLAPSE_ALL = "cta-courseeditor-nav-collapse-all",
  CTA_COURSEEDITOR_NAV_GROUP_TOGGLE_0 = "cta-courseeditor-nav-group-toggle-0",
  CTA_COURSEEDITOR_NAV_GROUP_TOGGLE_1 = "cta-courseeditor-nav-group-toggle-1",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_0 = "cta-courseeditor-nav-item-select-0-0",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_1 = "cta-courseeditor-nav-item-select-0-1",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_2 = "cta-courseeditor-nav-item-select-0-2",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_3 = "cta-courseeditor-nav-item-select-0-3",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_4 = "cta-courseeditor-nav-item-select-0-4",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_5 = "cta-courseeditor-nav-item-select-0-5",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_1_0 = "cta-courseeditor-nav-item-select-1-0",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_1_1 = "cta-courseeditor-nav-item-select-1-1",
  CTA_COURSEEDITOR_OPTION_0_ADD_MEDIA = "cta-courseeditor-option-0-add-media",
  CTA_COURSEEDITOR_OPTION_0_AI_REWRITE = "cta-courseeditor-option-0-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_1_ADD_MEDIA = "cta-courseeditor-option-1-add-media",
  CTA_COURSEEDITOR_OPTION_1_AI_REWRITE = "cta-courseeditor-option-1-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_2_ADD_MEDIA = "cta-courseeditor-option-2-add-media",
  CTA_COURSEEDITOR_OPTION_2_AI_REWRITE = "cta-courseeditor-option-2-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_3_ADD_MEDIA = "cta-courseeditor-option-3-add-media",
  CTA_COURSEEDITOR_OPTION_3_AI_REWRITE = "cta-courseeditor-option-3-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_ADD = "cta-courseeditor-option-add",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_1 = "cta-courseeditor-option-mark-correct-1",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_2 = "cta-courseeditor-option-mark-correct-2",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_3 = "cta-courseeditor-option-mark-correct-3",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_0 = "cta-courseeditor-preview-option-select-0",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_1 = "cta-courseeditor-preview-option-select-1",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_2 = "cta-courseeditor-preview-option-select-2",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_3 = "cta-courseeditor-preview-option-select-3",
  CTA_COURSEEDITOR_PREVIEW_REFRESH = "cta-courseeditor-preview-refresh",
  CTA_COURSEEDITOR_PUBLISH = "cta-courseeditor-publish",
  CTA_COURSEEDITOR_SAVE = "cta-courseeditor-save",
  CTA_COURSEEDITOR_STEM_AI_REWRITE = "cta-courseeditor-stem-ai-rewrite",
  CTA_COURSEEDITOR_STEM_MEDIA_LIBRARY = "cta-courseeditor-stem-media-library",
  CTA_COURSEEDITOR_STEM_PREVIEW = "cta-courseeditor-stem-preview",
  CTA_COURSEEDITOR_STEM_UPLOAD_MEDIA = "cta-courseeditor-stem-upload-media",
  CTA_COURSEEDITOR_TAB_EXERCISES = "cta-courseeditor-tab-exercises",
  CTA_COURSEEDITOR_TAB_STUDYTEXTS = "cta-courseeditor-tab-studytexts",
  CTA_CREATE_CLASS = "cta-create-class",
  CTA_ECGEN_CLEAR = "cta-ecgen-clear",
  CTA_ECGEN_SAVE_TO_COURSE = "cta-ecgen-save-to-course",
  CTA_ECGEN_SCOPE_COURSE = "cta-ecgen-scope-course",
  CTA_ECGEN_SCOPE_SELECTED = "cta-ecgen-scope-selected",
  CTA_ECGEN_SCOPE_SINGLE = "cta-ecgen-scope-single",
  CTA_ECGEN_SELECT_ALL = "cta-ecgen-select-all",
  CTA_ECGEN_START = "cta-ecgen-start",
  CTA_GENERATE_CLASS_CODE = "cta-generate-class-code",
  CTA_JOIN_CLASS = "cta-join-class",
  CTA_LINK_CHILD = "cta-link-child",
  CTA_REMOVE_STUDENT = "cta-remove-student",
  CTA_TEACHER_LESSON_KITS_AUTO_REPAIR = "cta-teacher-lesson-kits-auto-repair",
  CTA_TEACHER_LESSON_KITS_HTML = "cta-teacher-lesson-kits-html",
  CTA_TEACHER_LESSON_KITS_MODULE_ID = "cta-teacher-lesson-kits-module-id",
  CTA_TEACHER_LESSON_KITS_PROTOCOL = "cta-teacher-lesson-kits-protocol",
  CTA_TEACHER_LESSON_KITS_SUBMIT = "cta-teacher-lesson-kits-submit",
  CTA_TEACHER_MATERIALS_FILE = "cta-teacher-materials-file",
  CTA_TEACHER_MATERIALS_REFRESH = "cta-teacher-materials-refresh",
  CTA_TEACHER_MATERIALS_RESET = "cta-teacher-materials-reset",
  CTA_TEACHER_MATERIALS_TITLE = "cta-teacher-materials-title",
  CTA_TEACHER_MATERIALS_UPLOAD_AND_INGEST = "cta-teacher-materials-upload-and-ingest",
  CTA_TEACHER_STANDARDS_EXPORT = "cta-teacher-standards-export",
  CTA_TEACHER_STANDARDS_FILE = "cta-teacher-standards-file",
  CTA_TEACHER_STANDARDS_LOCALE = "cta-teacher-standards-locale",
  CTA_TEACHER_STANDARDS_MAP = "cta-teacher-standards-map",
  CTA_TEACHER_STANDARDS_REFRESH = "cta-teacher-standards-refresh",
  CTA_TEACHER_STANDARDS_RESET = "cta-teacher-standards-reset",
  CTA_TEACHER_STANDARDS_SELECT_MATERIAL = "cta-teacher-standards-select-material",
  CTA_TEACHER_STANDARDS_SELECT_STANDARDS = "cta-teacher-standards-select-standards",
  CTA_TEACHER_STANDARDS_TITLE = "cta-teacher-standards-title",
  CTA_TEACHER_STANDARDS_UPLOAD = "cta-teacher-standards-upload",
  CTA_UPDATE_GOAL = "cta-update-goal",
  CTA_VIEW_ACHIEVEMENT = "cta-view-achievement",
  CTA_VIEW_CHILD_GOALS = "cta-view-child-goals",
  CTA_VIEW_CHILD_PROGRESS = "cta-view-child-progress",
  CTA_VIEW_TIMELINE_EVENT = "cta-view-timeline-event",
  CTA_WYSIWYG_BACK_TO_SELECT = "cta-wysiwyg-back-to-select",
  CTA_WYSIWYG_EXPLANATION_AI_IMAGE = "cta-wysiwyg-explanation-ai-image",
  CTA_WYSIWYG_EXPLANATION_AI_REWRITE = "cta-wysiwyg-explanation-ai-rewrite",
  CTA_WYSIWYG_EXPLANATION_EDIT = "cta-wysiwyg-explanation-edit",
  CTA_WYSIWYG_EXPLANATION_UPLOAD_MEDIA = "cta-wysiwyg-explanation-upload-media",
  CTA_WYSIWYG_NAV_ITEM_0_0 = "cta-wysiwyg-nav-item-0-0",
  CTA_WYSIWYG_NAV_ITEM_0_1 = "cta-wysiwyg-nav-item-0-1",
  CTA_WYSIWYG_NAV_ITEM_0_2 = "cta-wysiwyg-nav-item-0-2",
  CTA_WYSIWYG_NAV_ITEM_0_3 = "cta-wysiwyg-nav-item-0-3",
  CTA_WYSIWYG_NAV_ITEM_0_4 = "cta-wysiwyg-nav-item-0-4",
  CTA_WYSIWYG_NAV_ITEM_0_5 = "cta-wysiwyg-nav-item-0-5",
  CTA_WYSIWYG_NAV_ITEM_1_0 = "cta-wysiwyg-nav-item-1-0",
  CTA_WYSIWYG_NAV_ITEM_1_1 = "cta-wysiwyg-nav-item-1-1",
  CTA_WYSIWYG_NEXT = "cta-wysiwyg-next",
  CTA_WYSIWYG_OPTION_AI_IMAGE_0 = "cta-wysiwyg-option-ai-image-0",
  CTA_WYSIWYG_OPTION_AI_IMAGE_1 = "cta-wysiwyg-option-ai-image-1",
  CTA_WYSIWYG_OPTION_AI_IMAGE_2 = "cta-wysiwyg-option-ai-image-2",
  CTA_WYSIWYG_OPTION_AI_IMAGE_3 = "cta-wysiwyg-option-ai-image-3",
  CTA_WYSIWYG_OPTION_AI_REWRITE_0 = "cta-wysiwyg-option-ai-rewrite-0",
  CTA_WYSIWYG_OPTION_AI_REWRITE_1 = "cta-wysiwyg-option-ai-rewrite-1",
  CTA_WYSIWYG_OPTION_AI_REWRITE_2 = "cta-wysiwyg-option-ai-rewrite-2",
  CTA_WYSIWYG_OPTION_AI_REWRITE_3 = "cta-wysiwyg-option-ai-rewrite-3",
  CTA_WYSIWYG_OPTION_EDIT_0 = "cta-wysiwyg-option-edit-0",
  CTA_WYSIWYG_OPTION_EDIT_1 = "cta-wysiwyg-option-edit-1",
  CTA_WYSIWYG_OPTION_EDIT_2 = "cta-wysiwyg-option-edit-2",
  CTA_WYSIWYG_OPTION_EDIT_3 = "cta-wysiwyg-option-edit-3",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_0 = "cta-wysiwyg-option-media-upload-0",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_1 = "cta-wysiwyg-option-media-upload-1",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_2 = "cta-wysiwyg-option-media-upload-2",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_3 = "cta-wysiwyg-option-media-upload-3",
  CTA_WYSIWYG_OPTION_SET_CORRECT_0 = "cta-wysiwyg-option-set-correct-0",
  CTA_WYSIWYG_OPTION_SET_CORRECT_1 = "cta-wysiwyg-option-set-correct-1",
  CTA_WYSIWYG_OPTION_SET_CORRECT_2 = "cta-wysiwyg-option-set-correct-2",
  CTA_WYSIWYG_OPTION_SET_CORRECT_3 = "cta-wysiwyg-option-set-correct-3",
  CTA_WYSIWYG_PREV = "cta-wysiwyg-prev",
  CTA_WYSIWYG_RETRY_LOAD = "cta-wysiwyg-retry-load",
  CTA_WYSIWYG_SAVE = "cta-wysiwyg-save",
  CTA_WYSIWYG_STEM_AI_IMAGE = "cta-wysiwyg-stem-ai-image",
  CTA_WYSIWYG_STEM_AI_REWRITE = "cta-wysiwyg-stem-ai-rewrite",
  CTA_WYSIWYG_STEM_EDIT = "cta-wysiwyg-stem-edit",
  CTA_WYSIWYG_STEM_UPLOAD_MEDIA = "cta-wysiwyg-stem-upload-media",
  NAV_ADMIN = "nav-admin",
  NAV_KIDS = "nav-kids",
  NAV_PARENTS = "nav-parents",
  NAV_SCHOOLS = "nav-schools",
}

export type CtaIdType = "cta-add-student" | "cta-admin-book-back" | "cta-admin-book-refresh" | "cta-admin-bookmissing-artifact-open" | "cta-admin-bookmissing-back" | "cta-admin-bookmissing-book-select" | "cta-admin-bookmissing-open-pdf" | "cta-admin-bookmissing-refresh" | "cta-admin-bookmissing-rerender" | "cta-admin-bookmissing-run-select" | "cta-admin-bookrun-back" | "cta-admin-bookrun-missing-ai-generate" | "cta-admin-bookrun-missing-refresh" | "cta-admin-bookrun-missing-upload" | "cta-admin-bookrun-refresh" | "cta-admin-books-ingest" | "cta-admin-books-ingest-bookid" | "cta-admin-books-ingest-canonical-file" | "cta-admin-books-ingest-figures-file" | "cta-admin-books-ingest-level" | "cta-admin-books-ingest-source" | "cta-admin-books-ingest-title" | "cta-admin-books-ingest-tokens-file" | "cta-admin-books-refresh" | "cta-admin-bookversion-allow-missing-images" | "cta-admin-bookversion-back" | "cta-admin-bookversion-bookgen-pro" | "cta-admin-bookversion-chapterindex" | "cta-admin-bookversion-create-overlay" | "cta-admin-bookversion-enqueue-book" | "cta-admin-bookversion-enqueue-chapter" | "cta-admin-bookversion-export-courseid" | "cta-admin-bookversion-export-studytexts" | "cta-admin-bookversion-new-overlay-label" | "cta-admin-bookversion-overlayid" | "cta-admin-bookversion-refresh" | "cta-admin-bookversion-render-provider" | "cta-admin-library-course-back" | "cta-admin-library-courses-format" | "cta-admin-library-courses-next" | "cta-admin-library-courses-open" | "cta-admin-library-courses-page-size" | "cta-admin-library-courses-prev" | "cta-admin-library-courses-refresh" | "cta-admin-library-courses-search" | "cta-admin-overlay-back" | "cta-admin-overlay-clear-selection" | "cta-admin-overlay-derived-courseid" | "cta-admin-overlay-generate-exercises" | "cta-admin-overlay-only-edited" | "cta-admin-overlay-refresh" | "cta-admin-overlay-save" | "cta-admin-overlay-search" | "cta-admin-overlay-select-all" | "cta-courseeditor-close" | "cta-courseeditor-command-archive" | "cta-courseeditor-command-audit-variants" | "cta-courseeditor-command-copilot-enrich" | "cta-courseeditor-command-copilot-variants" | "cta-courseeditor-command-delete" | "cta-courseeditor-command-discard" | "cta-courseeditor-command-generate-missing-variants" | "cta-courseeditor-command-localize" | "cta-courseeditor-command-palette" | "cta-courseeditor-command-publish" | "cta-courseeditor-command-repair" | "cta-courseeditor-command-save" | "cta-courseeditor-discard" | "cta-courseeditor-editor-tab-exercises" | "cta-courseeditor-editor-tab-explanation" | "cta-courseeditor-editor-tab-options" | "cta-courseeditor-editor-tab-stem" | "cta-courseeditor-exercises-generate" | "cta-courseeditor-explanation-ai-rewrite" | "cta-courseeditor-fab-add-image-ai" | "cta-courseeditor-fab-ai-rewrite-stem" | "cta-courseeditor-fab-generate-exercises" | "cta-courseeditor-fab-toggle" | "cta-courseeditor-item-add-image-ai" | "cta-courseeditor-item-fix-missing-images" | "cta-courseeditor-media-filter-all" | "cta-courseeditor-media-filter-audio" | "cta-courseeditor-media-filter-images" | "cta-courseeditor-media-filter-video" | "cta-courseeditor-media-select-0" | "cta-courseeditor-media-select-1" | "cta-courseeditor-media-select-2" | "cta-courseeditor-media-select-3" | "cta-courseeditor-media-select-4" | "cta-courseeditor-media-select-5" | "cta-courseeditor-media-toggle" | "cta-courseeditor-mode-select" | "cta-courseeditor-nav-add-group" | "cta-courseeditor-nav-collapse-all" | "cta-courseeditor-nav-group-toggle-0" | "cta-courseeditor-nav-group-toggle-1" | "cta-courseeditor-nav-item-select-0-0" | "cta-courseeditor-nav-item-select-0-1" | "cta-courseeditor-nav-item-select-0-2" | "cta-courseeditor-nav-item-select-0-3" | "cta-courseeditor-nav-item-select-0-4" | "cta-courseeditor-nav-item-select-0-5" | "cta-courseeditor-nav-item-select-1-0" | "cta-courseeditor-nav-item-select-1-1" | "cta-courseeditor-option-0-add-media" | "cta-courseeditor-option-0-ai-rewrite" | "cta-courseeditor-option-1-add-media" | "cta-courseeditor-option-1-ai-rewrite" | "cta-courseeditor-option-2-add-media" | "cta-courseeditor-option-2-ai-rewrite" | "cta-courseeditor-option-3-add-media" | "cta-courseeditor-option-3-ai-rewrite" | "cta-courseeditor-option-add" | "cta-courseeditor-option-mark-correct-1" | "cta-courseeditor-option-mark-correct-2" | "cta-courseeditor-option-mark-correct-3" | "cta-courseeditor-preview-option-select-0" | "cta-courseeditor-preview-option-select-1" | "cta-courseeditor-preview-option-select-2" | "cta-courseeditor-preview-option-select-3" | "cta-courseeditor-preview-refresh" | "cta-courseeditor-publish" | "cta-courseeditor-save" | "cta-courseeditor-stem-ai-rewrite" | "cta-courseeditor-stem-media-library" | "cta-courseeditor-stem-preview" | "cta-courseeditor-stem-upload-media" | "cta-courseeditor-tab-exercises" | "cta-courseeditor-tab-studytexts" | "cta-create-class" | "cta-ecgen-clear" | "cta-ecgen-save-to-course" | "cta-ecgen-scope-course" | "cta-ecgen-scope-selected" | "cta-ecgen-scope-single" | "cta-ecgen-select-all" | "cta-ecgen-start" | "cta-generate-class-code" | "cta-join-class" | "cta-link-child" | "cta-remove-student" | "cta-teacher-lesson-kits-auto-repair" | "cta-teacher-lesson-kits-html" | "cta-teacher-lesson-kits-module-id" | "cta-teacher-lesson-kits-protocol" | "cta-teacher-lesson-kits-submit" | "cta-teacher-materials-file" | "cta-teacher-materials-refresh" | "cta-teacher-materials-reset" | "cta-teacher-materials-title" | "cta-teacher-materials-upload-and-ingest" | "cta-teacher-standards-export" | "cta-teacher-standards-file" | "cta-teacher-standards-locale" | "cta-teacher-standards-map" | "cta-teacher-standards-refresh" | "cta-teacher-standards-reset" | "cta-teacher-standards-select-material" | "cta-teacher-standards-select-standards" | "cta-teacher-standards-title" | "cta-teacher-standards-upload" | "cta-update-goal" | "cta-view-achievement" | "cta-view-child-goals" | "cta-view-child-progress" | "cta-view-timeline-event" | "cta-wysiwyg-back-to-select" | "cta-wysiwyg-explanation-ai-image" | "cta-wysiwyg-explanation-ai-rewrite" | "cta-wysiwyg-explanation-edit" | "cta-wysiwyg-explanation-upload-media" | "cta-wysiwyg-nav-item-0-0" | "cta-wysiwyg-nav-item-0-1" | "cta-wysiwyg-nav-item-0-2" | "cta-wysiwyg-nav-item-0-3" | "cta-wysiwyg-nav-item-0-4" | "cta-wysiwyg-nav-item-0-5" | "cta-wysiwyg-nav-item-1-0" | "cta-wysiwyg-nav-item-1-1" | "cta-wysiwyg-next" | "cta-wysiwyg-option-ai-image-0" | "cta-wysiwyg-option-ai-image-1" | "cta-wysiwyg-option-ai-image-2" | "cta-wysiwyg-option-ai-image-3" | "cta-wysiwyg-option-ai-rewrite-0" | "cta-wysiwyg-option-ai-rewrite-1" | "cta-wysiwyg-option-ai-rewrite-2" | "cta-wysiwyg-option-ai-rewrite-3" | "cta-wysiwyg-option-edit-0" | "cta-wysiwyg-option-edit-1" | "cta-wysiwyg-option-edit-2" | "cta-wysiwyg-option-edit-3" | "cta-wysiwyg-option-media-upload-0" | "cta-wysiwyg-option-media-upload-1" | "cta-wysiwyg-option-media-upload-2" | "cta-wysiwyg-option-media-upload-3" | "cta-wysiwyg-option-set-correct-0" | "cta-wysiwyg-option-set-correct-1" | "cta-wysiwyg-option-set-correct-2" | "cta-wysiwyg-option-set-correct-3" | "cta-wysiwyg-prev" | "cta-wysiwyg-retry-load" | "cta-wysiwyg-save" | "cta-wysiwyg-stem-ai-image" | "cta-wysiwyg-stem-ai-rewrite" | "cta-wysiwyg-stem-edit" | "cta-wysiwyg-stem-upload-media" | "nav-admin" | "nav-kids" | "nav-parents" | "nav-schools";

export const CTA_IDS = {
  CTA_ADD_STUDENT: "cta-add-student",
  CTA_ADMIN_BOOK_BACK: "cta-admin-book-back",
  CTA_ADMIN_BOOK_REFRESH: "cta-admin-book-refresh",
  CTA_ADMIN_BOOKMISSING_ARTIFACT_OPEN: "cta-admin-bookmissing-artifact-open",
  CTA_ADMIN_BOOKMISSING_BACK: "cta-admin-bookmissing-back",
  CTA_ADMIN_BOOKMISSING_BOOK_SELECT: "cta-admin-bookmissing-book-select",
  CTA_ADMIN_BOOKMISSING_OPEN_PDF: "cta-admin-bookmissing-open-pdf",
  CTA_ADMIN_BOOKMISSING_REFRESH: "cta-admin-bookmissing-refresh",
  CTA_ADMIN_BOOKMISSING_RERENDER: "cta-admin-bookmissing-rerender",
  CTA_ADMIN_BOOKMISSING_RUN_SELECT: "cta-admin-bookmissing-run-select",
  CTA_ADMIN_BOOKRUN_BACK: "cta-admin-bookrun-back",
  CTA_ADMIN_BOOKRUN_MISSING_AI_GENERATE: "cta-admin-bookrun-missing-ai-generate",
  CTA_ADMIN_BOOKRUN_MISSING_REFRESH: "cta-admin-bookrun-missing-refresh",
  CTA_ADMIN_BOOKRUN_MISSING_UPLOAD: "cta-admin-bookrun-missing-upload",
  CTA_ADMIN_BOOKRUN_REFRESH: "cta-admin-bookrun-refresh",
  CTA_ADMIN_BOOKS_INGEST: "cta-admin-books-ingest",
  CTA_ADMIN_BOOKS_INGEST_BOOKID: "cta-admin-books-ingest-bookid",
  CTA_ADMIN_BOOKS_INGEST_CANONICAL_FILE: "cta-admin-books-ingest-canonical-file",
  CTA_ADMIN_BOOKS_INGEST_FIGURES_FILE: "cta-admin-books-ingest-figures-file",
  CTA_ADMIN_BOOKS_INGEST_LEVEL: "cta-admin-books-ingest-level",
  CTA_ADMIN_BOOKS_INGEST_SOURCE: "cta-admin-books-ingest-source",
  CTA_ADMIN_BOOKS_INGEST_TITLE: "cta-admin-books-ingest-title",
  CTA_ADMIN_BOOKS_INGEST_TOKENS_FILE: "cta-admin-books-ingest-tokens-file",
  CTA_ADMIN_BOOKS_REFRESH: "cta-admin-books-refresh",
  CTA_ADMIN_BOOKVERSION_ALLOW_MISSING_IMAGES: "cta-admin-bookversion-allow-missing-images",
  CTA_ADMIN_BOOKVERSION_BACK: "cta-admin-bookversion-back",
  CTA_ADMIN_BOOKVERSION_BOOKGEN_PRO: "cta-admin-bookversion-bookgen-pro",
  CTA_ADMIN_BOOKVERSION_CHAPTERINDEX: "cta-admin-bookversion-chapterindex",
  CTA_ADMIN_BOOKVERSION_CREATE_OVERLAY: "cta-admin-bookversion-create-overlay",
  CTA_ADMIN_BOOKVERSION_ENQUEUE_BOOK: "cta-admin-bookversion-enqueue-book",
  CTA_ADMIN_BOOKVERSION_ENQUEUE_CHAPTER: "cta-admin-bookversion-enqueue-chapter",
  CTA_ADMIN_BOOKVERSION_EXPORT_COURSEID: "cta-admin-bookversion-export-courseid",
  CTA_ADMIN_BOOKVERSION_EXPORT_STUDYTEXTS: "cta-admin-bookversion-export-studytexts",
  CTA_ADMIN_BOOKVERSION_NEW_OVERLAY_LABEL: "cta-admin-bookversion-new-overlay-label",
  CTA_ADMIN_BOOKVERSION_OVERLAYID: "cta-admin-bookversion-overlayid",
  CTA_ADMIN_BOOKVERSION_REFRESH: "cta-admin-bookversion-refresh",
  CTA_ADMIN_BOOKVERSION_RENDER_PROVIDER: "cta-admin-bookversion-render-provider",
  CTA_ADMIN_LIBRARY_COURSE_BACK: "cta-admin-library-course-back",
  CTA_ADMIN_LIBRARY_COURSES_FORMAT: "cta-admin-library-courses-format",
  CTA_ADMIN_LIBRARY_COURSES_NEXT: "cta-admin-library-courses-next",
  CTA_ADMIN_LIBRARY_COURSES_OPEN: "cta-admin-library-courses-open",
  CTA_ADMIN_LIBRARY_COURSES_PAGE_SIZE: "cta-admin-library-courses-page-size",
  CTA_ADMIN_LIBRARY_COURSES_PREV: "cta-admin-library-courses-prev",
  CTA_ADMIN_LIBRARY_COURSES_REFRESH: "cta-admin-library-courses-refresh",
  CTA_ADMIN_LIBRARY_COURSES_SEARCH: "cta-admin-library-courses-search",
  CTA_ADMIN_OVERLAY_BACK: "cta-admin-overlay-back",
  CTA_ADMIN_OVERLAY_CLEAR_SELECTION: "cta-admin-overlay-clear-selection",
  CTA_ADMIN_OVERLAY_DERIVED_COURSEID: "cta-admin-overlay-derived-courseid",
  CTA_ADMIN_OVERLAY_GENERATE_EXERCISES: "cta-admin-overlay-generate-exercises",
  CTA_ADMIN_OVERLAY_ONLY_EDITED: "cta-admin-overlay-only-edited",
  CTA_ADMIN_OVERLAY_REFRESH: "cta-admin-overlay-refresh",
  CTA_ADMIN_OVERLAY_SAVE: "cta-admin-overlay-save",
  CTA_ADMIN_OVERLAY_SEARCH: "cta-admin-overlay-search",
  CTA_ADMIN_OVERLAY_SELECT_ALL: "cta-admin-overlay-select-all",
  CTA_COURSEEDITOR_CLOSE: "cta-courseeditor-close",
  CTA_COURSEEDITOR_COMMAND_ARCHIVE: "cta-courseeditor-command-archive",
  CTA_COURSEEDITOR_COMMAND_AUDIT_VARIANTS: "cta-courseeditor-command-audit-variants",
  CTA_COURSEEDITOR_COMMAND_COPILOT_ENRICH: "cta-courseeditor-command-copilot-enrich",
  CTA_COURSEEDITOR_COMMAND_COPILOT_VARIANTS: "cta-courseeditor-command-copilot-variants",
  CTA_COURSEEDITOR_COMMAND_DELETE: "cta-courseeditor-command-delete",
  CTA_COURSEEDITOR_COMMAND_DISCARD: "cta-courseeditor-command-discard",
  CTA_COURSEEDITOR_COMMAND_GENERATE_MISSING_VARIANTS: "cta-courseeditor-command-generate-missing-variants",
  CTA_COURSEEDITOR_COMMAND_LOCALIZE: "cta-courseeditor-command-localize",
  CTA_COURSEEDITOR_COMMAND_PALETTE: "cta-courseeditor-command-palette",
  CTA_COURSEEDITOR_COMMAND_PUBLISH: "cta-courseeditor-command-publish",
  CTA_COURSEEDITOR_COMMAND_REPAIR: "cta-courseeditor-command-repair",
  CTA_COURSEEDITOR_COMMAND_SAVE: "cta-courseeditor-command-save",
  CTA_COURSEEDITOR_DISCARD: "cta-courseeditor-discard",
  CTA_COURSEEDITOR_EDITOR_TAB_EXERCISES: "cta-courseeditor-editor-tab-exercises",
  CTA_COURSEEDITOR_EDITOR_TAB_EXPLANATION: "cta-courseeditor-editor-tab-explanation",
  CTA_COURSEEDITOR_EDITOR_TAB_OPTIONS: "cta-courseeditor-editor-tab-options",
  CTA_COURSEEDITOR_EDITOR_TAB_STEM: "cta-courseeditor-editor-tab-stem",
  CTA_COURSEEDITOR_EXERCISES_GENERATE: "cta-courseeditor-exercises-generate",
  CTA_COURSEEDITOR_EXPLANATION_AI_REWRITE: "cta-courseeditor-explanation-ai-rewrite",
  CTA_COURSEEDITOR_FAB_ADD_IMAGE_AI: "cta-courseeditor-fab-add-image-ai",
  CTA_COURSEEDITOR_FAB_AI_REWRITE_STEM: "cta-courseeditor-fab-ai-rewrite-stem",
  CTA_COURSEEDITOR_FAB_GENERATE_EXERCISES: "cta-courseeditor-fab-generate-exercises",
  CTA_COURSEEDITOR_FAB_TOGGLE: "cta-courseeditor-fab-toggle",
  CTA_COURSEEDITOR_ITEM_ADD_IMAGE_AI: "cta-courseeditor-item-add-image-ai",
  CTA_COURSEEDITOR_ITEM_FIX_MISSING_IMAGES: "cta-courseeditor-item-fix-missing-images",
  CTA_COURSEEDITOR_MEDIA_FILTER_ALL: "cta-courseeditor-media-filter-all",
  CTA_COURSEEDITOR_MEDIA_FILTER_AUDIO: "cta-courseeditor-media-filter-audio",
  CTA_COURSEEDITOR_MEDIA_FILTER_IMAGES: "cta-courseeditor-media-filter-images",
  CTA_COURSEEDITOR_MEDIA_FILTER_VIDEO: "cta-courseeditor-media-filter-video",
  CTA_COURSEEDITOR_MEDIA_SELECT_0: "cta-courseeditor-media-select-0",
  CTA_COURSEEDITOR_MEDIA_SELECT_1: "cta-courseeditor-media-select-1",
  CTA_COURSEEDITOR_MEDIA_SELECT_2: "cta-courseeditor-media-select-2",
  CTA_COURSEEDITOR_MEDIA_SELECT_3: "cta-courseeditor-media-select-3",
  CTA_COURSEEDITOR_MEDIA_SELECT_4: "cta-courseeditor-media-select-4",
  CTA_COURSEEDITOR_MEDIA_SELECT_5: "cta-courseeditor-media-select-5",
  CTA_COURSEEDITOR_MEDIA_TOGGLE: "cta-courseeditor-media-toggle",
  CTA_COURSEEDITOR_MODE_SELECT: "cta-courseeditor-mode-select",
  CTA_COURSEEDITOR_NAV_ADD_GROUP: "cta-courseeditor-nav-add-group",
  CTA_COURSEEDITOR_NAV_COLLAPSE_ALL: "cta-courseeditor-nav-collapse-all",
  CTA_COURSEEDITOR_NAV_GROUP_TOGGLE_0: "cta-courseeditor-nav-group-toggle-0",
  CTA_COURSEEDITOR_NAV_GROUP_TOGGLE_1: "cta-courseeditor-nav-group-toggle-1",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_0: "cta-courseeditor-nav-item-select-0-0",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_1: "cta-courseeditor-nav-item-select-0-1",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_2: "cta-courseeditor-nav-item-select-0-2",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_3: "cta-courseeditor-nav-item-select-0-3",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_4: "cta-courseeditor-nav-item-select-0-4",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_0_5: "cta-courseeditor-nav-item-select-0-5",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_1_0: "cta-courseeditor-nav-item-select-1-0",
  CTA_COURSEEDITOR_NAV_ITEM_SELECT_1_1: "cta-courseeditor-nav-item-select-1-1",
  CTA_COURSEEDITOR_OPTION_0_ADD_MEDIA: "cta-courseeditor-option-0-add-media",
  CTA_COURSEEDITOR_OPTION_0_AI_REWRITE: "cta-courseeditor-option-0-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_1_ADD_MEDIA: "cta-courseeditor-option-1-add-media",
  CTA_COURSEEDITOR_OPTION_1_AI_REWRITE: "cta-courseeditor-option-1-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_2_ADD_MEDIA: "cta-courseeditor-option-2-add-media",
  CTA_COURSEEDITOR_OPTION_2_AI_REWRITE: "cta-courseeditor-option-2-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_3_ADD_MEDIA: "cta-courseeditor-option-3-add-media",
  CTA_COURSEEDITOR_OPTION_3_AI_REWRITE: "cta-courseeditor-option-3-ai-rewrite",
  CTA_COURSEEDITOR_OPTION_ADD: "cta-courseeditor-option-add",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_1: "cta-courseeditor-option-mark-correct-1",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_2: "cta-courseeditor-option-mark-correct-2",
  CTA_COURSEEDITOR_OPTION_MARK_CORRECT_3: "cta-courseeditor-option-mark-correct-3",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_0: "cta-courseeditor-preview-option-select-0",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_1: "cta-courseeditor-preview-option-select-1",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_2: "cta-courseeditor-preview-option-select-2",
  CTA_COURSEEDITOR_PREVIEW_OPTION_SELECT_3: "cta-courseeditor-preview-option-select-3",
  CTA_COURSEEDITOR_PREVIEW_REFRESH: "cta-courseeditor-preview-refresh",
  CTA_COURSEEDITOR_PUBLISH: "cta-courseeditor-publish",
  CTA_COURSEEDITOR_SAVE: "cta-courseeditor-save",
  CTA_COURSEEDITOR_STEM_AI_REWRITE: "cta-courseeditor-stem-ai-rewrite",
  CTA_COURSEEDITOR_STEM_MEDIA_LIBRARY: "cta-courseeditor-stem-media-library",
  CTA_COURSEEDITOR_STEM_PREVIEW: "cta-courseeditor-stem-preview",
  CTA_COURSEEDITOR_STEM_UPLOAD_MEDIA: "cta-courseeditor-stem-upload-media",
  CTA_COURSEEDITOR_TAB_EXERCISES: "cta-courseeditor-tab-exercises",
  CTA_COURSEEDITOR_TAB_STUDYTEXTS: "cta-courseeditor-tab-studytexts",
  CTA_CREATE_CLASS: "cta-create-class",
  CTA_ECGEN_CLEAR: "cta-ecgen-clear",
  CTA_ECGEN_SAVE_TO_COURSE: "cta-ecgen-save-to-course",
  CTA_ECGEN_SCOPE_COURSE: "cta-ecgen-scope-course",
  CTA_ECGEN_SCOPE_SELECTED: "cta-ecgen-scope-selected",
  CTA_ECGEN_SCOPE_SINGLE: "cta-ecgen-scope-single",
  CTA_ECGEN_SELECT_ALL: "cta-ecgen-select-all",
  CTA_ECGEN_START: "cta-ecgen-start",
  CTA_GENERATE_CLASS_CODE: "cta-generate-class-code",
  CTA_JOIN_CLASS: "cta-join-class",
  CTA_LINK_CHILD: "cta-link-child",
  CTA_REMOVE_STUDENT: "cta-remove-student",
  CTA_TEACHER_LESSON_KITS_AUTO_REPAIR: "cta-teacher-lesson-kits-auto-repair",
  CTA_TEACHER_LESSON_KITS_HTML: "cta-teacher-lesson-kits-html",
  CTA_TEACHER_LESSON_KITS_MODULE_ID: "cta-teacher-lesson-kits-module-id",
  CTA_TEACHER_LESSON_KITS_PROTOCOL: "cta-teacher-lesson-kits-protocol",
  CTA_TEACHER_LESSON_KITS_SUBMIT: "cta-teacher-lesson-kits-submit",
  CTA_TEACHER_MATERIALS_FILE: "cta-teacher-materials-file",
  CTA_TEACHER_MATERIALS_REFRESH: "cta-teacher-materials-refresh",
  CTA_TEACHER_MATERIALS_RESET: "cta-teacher-materials-reset",
  CTA_TEACHER_MATERIALS_TITLE: "cta-teacher-materials-title",
  CTA_TEACHER_MATERIALS_UPLOAD_AND_INGEST: "cta-teacher-materials-upload-and-ingest",
  CTA_TEACHER_STANDARDS_EXPORT: "cta-teacher-standards-export",
  CTA_TEACHER_STANDARDS_FILE: "cta-teacher-standards-file",
  CTA_TEACHER_STANDARDS_LOCALE: "cta-teacher-standards-locale",
  CTA_TEACHER_STANDARDS_MAP: "cta-teacher-standards-map",
  CTA_TEACHER_STANDARDS_REFRESH: "cta-teacher-standards-refresh",
  CTA_TEACHER_STANDARDS_RESET: "cta-teacher-standards-reset",
  CTA_TEACHER_STANDARDS_SELECT_MATERIAL: "cta-teacher-standards-select-material",
  CTA_TEACHER_STANDARDS_SELECT_STANDARDS: "cta-teacher-standards-select-standards",
  CTA_TEACHER_STANDARDS_TITLE: "cta-teacher-standards-title",
  CTA_TEACHER_STANDARDS_UPLOAD: "cta-teacher-standards-upload",
  CTA_UPDATE_GOAL: "cta-update-goal",
  CTA_VIEW_ACHIEVEMENT: "cta-view-achievement",
  CTA_VIEW_CHILD_GOALS: "cta-view-child-goals",
  CTA_VIEW_CHILD_PROGRESS: "cta-view-child-progress",
  CTA_VIEW_TIMELINE_EVENT: "cta-view-timeline-event",
  CTA_WYSIWYG_BACK_TO_SELECT: "cta-wysiwyg-back-to-select",
  CTA_WYSIWYG_EXPLANATION_AI_IMAGE: "cta-wysiwyg-explanation-ai-image",
  CTA_WYSIWYG_EXPLANATION_AI_REWRITE: "cta-wysiwyg-explanation-ai-rewrite",
  CTA_WYSIWYG_EXPLANATION_EDIT: "cta-wysiwyg-explanation-edit",
  CTA_WYSIWYG_EXPLANATION_UPLOAD_MEDIA: "cta-wysiwyg-explanation-upload-media",
  CTA_WYSIWYG_NAV_ITEM_0_0: "cta-wysiwyg-nav-item-0-0",
  CTA_WYSIWYG_NAV_ITEM_0_1: "cta-wysiwyg-nav-item-0-1",
  CTA_WYSIWYG_NAV_ITEM_0_2: "cta-wysiwyg-nav-item-0-2",
  CTA_WYSIWYG_NAV_ITEM_0_3: "cta-wysiwyg-nav-item-0-3",
  CTA_WYSIWYG_NAV_ITEM_0_4: "cta-wysiwyg-nav-item-0-4",
  CTA_WYSIWYG_NAV_ITEM_0_5: "cta-wysiwyg-nav-item-0-5",
  CTA_WYSIWYG_NAV_ITEM_1_0: "cta-wysiwyg-nav-item-1-0",
  CTA_WYSIWYG_NAV_ITEM_1_1: "cta-wysiwyg-nav-item-1-1",
  CTA_WYSIWYG_NEXT: "cta-wysiwyg-next",
  CTA_WYSIWYG_OPTION_AI_IMAGE_0: "cta-wysiwyg-option-ai-image-0",
  CTA_WYSIWYG_OPTION_AI_IMAGE_1: "cta-wysiwyg-option-ai-image-1",
  CTA_WYSIWYG_OPTION_AI_IMAGE_2: "cta-wysiwyg-option-ai-image-2",
  CTA_WYSIWYG_OPTION_AI_IMAGE_3: "cta-wysiwyg-option-ai-image-3",
  CTA_WYSIWYG_OPTION_AI_REWRITE_0: "cta-wysiwyg-option-ai-rewrite-0",
  CTA_WYSIWYG_OPTION_AI_REWRITE_1: "cta-wysiwyg-option-ai-rewrite-1",
  CTA_WYSIWYG_OPTION_AI_REWRITE_2: "cta-wysiwyg-option-ai-rewrite-2",
  CTA_WYSIWYG_OPTION_AI_REWRITE_3: "cta-wysiwyg-option-ai-rewrite-3",
  CTA_WYSIWYG_OPTION_EDIT_0: "cta-wysiwyg-option-edit-0",
  CTA_WYSIWYG_OPTION_EDIT_1: "cta-wysiwyg-option-edit-1",
  CTA_WYSIWYG_OPTION_EDIT_2: "cta-wysiwyg-option-edit-2",
  CTA_WYSIWYG_OPTION_EDIT_3: "cta-wysiwyg-option-edit-3",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_0: "cta-wysiwyg-option-media-upload-0",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_1: "cta-wysiwyg-option-media-upload-1",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_2: "cta-wysiwyg-option-media-upload-2",
  CTA_WYSIWYG_OPTION_MEDIA_UPLOAD_3: "cta-wysiwyg-option-media-upload-3",
  CTA_WYSIWYG_OPTION_SET_CORRECT_0: "cta-wysiwyg-option-set-correct-0",
  CTA_WYSIWYG_OPTION_SET_CORRECT_1: "cta-wysiwyg-option-set-correct-1",
  CTA_WYSIWYG_OPTION_SET_CORRECT_2: "cta-wysiwyg-option-set-correct-2",
  CTA_WYSIWYG_OPTION_SET_CORRECT_3: "cta-wysiwyg-option-set-correct-3",
  CTA_WYSIWYG_PREV: "cta-wysiwyg-prev",
  CTA_WYSIWYG_RETRY_LOAD: "cta-wysiwyg-retry-load",
  CTA_WYSIWYG_SAVE: "cta-wysiwyg-save",
  CTA_WYSIWYG_STEM_AI_IMAGE: "cta-wysiwyg-stem-ai-image",
  CTA_WYSIWYG_STEM_AI_REWRITE: "cta-wysiwyg-stem-ai-rewrite",
  CTA_WYSIWYG_STEM_EDIT: "cta-wysiwyg-stem-edit",
  CTA_WYSIWYG_STEM_UPLOAD_MEDIA: "cta-wysiwyg-stem-upload-media",
  NAV_ADMIN: "nav-admin",
  NAV_KIDS: "nav-kids",
  NAV_PARENTS: "nav-parents",
  NAV_SCHOOLS: "nav-schools"
} as const;

// Type guard
export function isValidCtaId(id: string): id is CtaIdType {
  return Object.values(CtaId).includes(id as CtaId);
}
