
// AUTO-GENERATED by scaffold-manifest.ts
import { JobExecutor, JobContext } from './types.ts';

export class GeneratedGenerateSubtasks implements JobExecutor {
  async execute(context: JobContext): Promise<any> {
    const { payload } = context;
    
    // 1. Interpolate Prompt
    let prompt = `Break down '{{title}}' into 3 actionable subtasks.`;
    if (payload) {
      Object.keys(payload).forEach(key => {
        const val = typeof payload[key] === 'object' ? JSON.stringify(payload[key]) : String(payload[key] || '');
        prompt = prompt.replace(new RegExp('{{' + key + '}}', 'g'), val);
      });
    }

    // 2. Call LLM (Simplified for seed)
    const apiKey = Deno.env.get('OPENAI_API_KEY');
    if (!apiKey) {
       throw new Error("Missing OPENAI_API_KEY");
    }

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4o',
        messages: [{ role: 'system', content: prompt }],
        response_format: { type: "json_object" }
      })
    });

    if (!response.ok) {
      const err = await response.text();
      throw new Error(`LLM Call Failed: ${err}`);
    }

    const data = await response.json();
    try {
       return JSON.parse(data.choices[0].message.content);
    } catch (_e) {
       return { raw: data.choices[0].message.content };
    }
  }
}
