// supabase/functions/ai-job-runner/registry.ts
// ⚠️ AUTO-GENERATED by scaffold-manifest.ts
import { JobExecutor } from './strategies/types.ts';
import { GeneratedDraftAssignmentPlan } from './strategies/gen-draft_assignment_plan.ts';
import { GeneratedAiCourseGenerate } from './strategies/gen-ai_course_generate.ts';
import { GeneratedGuardCourse } from './strategies/gen-guard_course.ts';
import { GeneratedCompileMockups } from './strategies/gen-compile_mockups.ts';
import { GeneratedPlanMatrixRun } from './strategies/gen-plan_matrix_run.ts';

export const JobRegistry: Record<string, JobExecutor> = {
  'draft_assignment_plan': new GeneratedDraftAssignmentPlan(),
  'ai_course_generate': new GeneratedAiCourseGenerate(),
  'guard_course': new GeneratedGuardCourse(),
  'compile_mockups': new GeneratedCompileMockups(),
  'plan_matrix_run': new GeneratedPlanMatrixRun(),
};
