// supabase/functions/ai-job-runner/registry.ts
// ⚠️ AUTO-GENERATED by scaffold-manifest.ts
import { JobExecutor } from './strategies/types.ts';
import { GeneratedBookIngestVersion } from './strategies/gen-book_ingest_version.ts';
import { GeneratedBookRenderChapter } from './strategies/gen-book_render_chapter.ts';
import { GeneratedBookRenderFull } from './strategies/gen-book_render_full.ts';
import { BookGenerateFull } from './strategies/book_generate_full.ts';
import { BookGenerateChapter } from './strategies/book_generate_chapter.ts';
import { BookGenerateSection } from './strategies/book_generate_section.ts';
import { BookGenerateIndex } from './strategies/book_generate_index.ts';
import { BookGenerateGlossary } from './strategies/book_generate_glossary.ts';
import { GeneratedDraftAssignmentPlan } from './strategies/gen-draft_assignment_plan.ts';
import { GeneratedAiCourseGenerate } from './strategies/gen-ai_course_generate.ts';
import { GeneratedGuardCourse } from './strategies/gen-guard_course.ts';
import { GeneratedCompileMockups } from './strategies/gen-compile_mockups.ts';
import { GeneratedPlanMatrixRun } from './strategies/gen-plan_matrix_run.ts';
import { MaterialIngest } from './strategies/material_ingest.ts';
import { MaterialAnalyze } from './strategies/material_analyze.ts';
import { LessonkitBuild } from './strategies/lessonkit_build.ts';
import { StandardsIngest } from './strategies/standards_ingest.ts';
import { StandardsMap } from './strategies/standards_map.ts';
import { StandardsExport } from './strategies/standards_export.ts';
import { MesCorpusIndex } from './strategies/mes_corpus_index.ts';

export const JobRegistry: Record<string, JobExecutor> = {
  'book_ingest_version': new GeneratedBookIngestVersion(),
  'book_render_chapter': new GeneratedBookRenderChapter(),
  'book_render_full': new GeneratedBookRenderFull(),
  'book_generate_full': new BookGenerateFull(),
  'book_generate_chapter': new BookGenerateChapter(),
  'book_generate_section': new BookGenerateSection(),
  'book_generate_index': new BookGenerateIndex(),
  'book_generate_glossary': new BookGenerateGlossary(),
  'draft_assignment_plan': new GeneratedDraftAssignmentPlan(),
  'ai_course_generate': new GeneratedAiCourseGenerate(),
  'guard_course': new GeneratedGuardCourse(),
  'compile_mockups': new GeneratedCompileMockups(),
  'plan_matrix_run': new GeneratedPlanMatrixRun(),
  'material_ingest': new MaterialIngest(),
  'material_analyze': new MaterialAnalyze(),
  'lessonkit_build': new LessonkitBuild(),
  'standards_ingest': new StandardsIngest(),
  'standards_map': new StandardsMap(),
  'standards_export': new StandardsExport(),
  'mes_corpus_index': new MesCorpusIndex(),
};
