// This file is automatically generated. Do not edit it directly.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createClient } from '@supabase/supabase-js';
import { getRuntimeConfigSync } from '@/lib/runtimeConfig';
// Avoid strict typing against generated Database types in varied environments
// to prevent build-time type mismatches when tables differ.

// Read config from env first, then runtime /app-config.json (Lovable-style hosts).
const SUPABASE_URL: string | undefined =
  (import.meta as any).env?.VITE_SUPABASE_URL ||
  getRuntimeConfigSync()?.supabase?.url;
const SUPABASE_KEY: string | undefined =
  (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY ||
  (import.meta as any).env?.VITE_SUPABASE_ANON_KEY ||
  getRuntimeConfigSync()?.supabase?.publishableKey;

// IgniteZero: FAIL LOUDLY if credentials missing (mock mode is forbidden).
if (!SUPABASE_URL || !SUPABASE_KEY) {
  throw new Error(
    '❌ BLOCKED: Missing Supabase credentials.\n' +
      '   Configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY).\n' +
      '   (Lovable/preview hosts may provide these via /app-config.json.)'
  );
}

// Safe localStorage wrapper to handle restricted iframe environments
const safeStorage = (() => {
  try {
    // Test localStorage access
    const testKey = '__supabase_test__';
    localStorage.setItem(testKey, 'test');
    localStorage.removeItem(testKey);
    return localStorage;
  } catch {
    // Return in-memory fallback if localStorage is blocked
    const memoryStore: Record<string, string> = {};
    return {
      getItem: (key: string) => memoryStore[key] || null,
      setItem: (key: string, value: string) => { memoryStore[key] = value; },
      removeItem: (key: string) => { delete memoryStore[key]; },
    };
  }
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<any>(SUPABASE_URL as string, SUPABASE_KEY as string, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

/**
 * Helper function to get the current user's access token
 */
export async function getAccessToken(): Promise<string | null> {
  const { data: { session } } = await supabase.auth.getSession();
  return session?.access_token ?? null;
}