// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Avoid strict typing against generated Database types in varied environments
// to prevent build-time type mismatches when tables differ.

// Hardcoded credentials (works everywhere without env vars)
const HARDCODED_URL = 'https://xlslksprdjsxawvcikfk.supabase.co';
const HARDCODED_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsc2xrc3ByZGpzeGF3dmNpa2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MTMxMzEsImV4cCI6MjA3OTI4OTEzMX0.1Jo8F2o42z_K7PXeHrEp28AwbomBkrrOJh1_t3vU0iM';

const SUPABASE_URL: string = (import.meta as any).env?.VITE_SUPABASE_URL || HARDCODED_URL;
// Accept either PUBLISHABLE or ANON key names for flexibility
const SUPABASE_KEY: string =
  (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY ||
  (import.meta as any).env?.VITE_SUPABASE_ANON_KEY ||
  HARDCODED_ANON_KEY;
// Default to mock mode unless explicitly set to 'false' to avoid iframe/localStorage issues
const USE_MOCK = String((import.meta as any).env?.VITE_USE_MOCK) !== 'false';

// In mock mode, short-circuit all Supabase calls to avoid network dependency during E2E.
const mockSupabase = {
  functions: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    invoke: async (): Promise<{ data: any; error: null }> => ({ data: null, error: null }),
  },
  auth: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    getUser: async (): Promise<{ data: any; error: null }> => ({ data: { user: null }, error: null }),
    getSession: async (): Promise<{ data: { session: null }; error: null }> => ({ data: { session: null }, error: null }),
    signInWithPassword: async (): Promise<{ data: any; error: null }> => ({ data: { user: null, session: null }, error: null }),
    signUp: async (): Promise<{ data: any; error: null }> => ({ data: { user: null, session: null }, error: null }),
    signOut: async (): Promise<{ error: null }> => ({ error: null }),
    onAuthStateChange: (_callback: any) => {
      // Return unsubscribe function
      return { data: { subscription: { unsubscribe: () => {} } } };
    },
  },
  from: () => ({
    select: () => ({ data: [], error: null }),
    insert: () => ({ data: null, error: null }),
    update: () => ({ data: null, error: null }),
    delete: () => ({ data: null, error: null }),
  }),
  storage: {
    from: () => ({
      upload: async () => ({ data: null, error: null }),
      getPublicUrl: () => ({ data: { publicUrl: 'https://mock.storage.url/file' } }),
    }),
  },
} as any;

// Safe localStorage wrapper to handle restricted iframe environments
const safeStorage = (() => {
  try {
    // Test localStorage access
    const testKey = '__supabase_test__';
    localStorage.setItem(testKey, 'test');
    localStorage.removeItem(testKey);
    return localStorage;
  } catch {
    // Return in-memory fallback if localStorage is blocked
    const memoryStore: Record<string, string> = {};
    return {
      getItem: (key: string) => memoryStore[key] || null,
      setItem: (key: string, value: string) => { memoryStore[key] = value; },
      removeItem: (key: string) => { delete memoryStore[key]; },
    };
  }
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = USE_MOCK
  ? mockSupabase
  : createClient<any>(
      SUPABASE_URL,
      SUPABASE_KEY,
      {
        auth: {
          storage: safeStorage,
          persistSession: true,
          autoRefreshToken: true,
        }
      }
    );
